import React,{useEffect,useRef,useState} from 'react';
import {useICU} from '../context/ICUContext.jsx';
import {SUMMARY_SECTIONS,DAY_SECTIONS,CHART_HANDOFF,chartToken,chartPrompt,organizeFromRecords,validateChart} from '../core/chartOrganization.js';
import {mergeDailyRecords} from '../core/dailyHistory.js';
import {mobileLabel,isoToBR} from '../core/icuStore.js';
import {copyText} from '../core/prescricao.js';
import {requestClinicalAI} from '../services/productionAI.js';
const handoffLabels=['HD','HMP','HMA','CD / METAS','Pendências'];
export default function ChartOrganizer({bed}){
 const {actions,saveStatus,apiMeta,state}=useICU();
 const [text,setText]=useState(''),[response,setResponse]=useState(''),[preview,setPreview]=useState(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const source=JSON.stringify(bed),latest=useRef(source),abort=useRef(null);latest.current=source;
 const ready=saveStatus==='saved'&&!state.reviewEpisodeId&&!busy;
 useEffect(()=>{setPreview(null);setText('');setResponse('');setNotice('');setBusy(false);return()=>abort.current?.abort();},[bed.patientId,bed.episodeId]);
 useEffect(()=>{if(preview&&(preview.source!==source||preview.version!==apiMeta?.version)){setPreview(null);setNotice('Os registros mudaram após a preparação. Gere e revise novamente.');}},[source,apiMeta?.version]);
 const capture=async()=>{const original=latest.current,token=await chartToken(bed);if(latest.current!==original)throw Error('Os registros mudaram. Aguarde o salvamento e tente novamente.');return {source:original,token,version:apiMeta.version};};
 const prepare=(doc,captured,origin)=>{if(latest.current!==captured.source)throw Error('Paciente, internação, leito ou registros mudaram. Gere novamente.');const data=validateChart(doc,bed);if(data.review_token!==captured.token)throw Error('Resposta pertence a uma versão anterior do prontuário. Copie um novo prompt.');setPreview({document:data,...captured,origin,sourceText:text,choices:{summary:origin==='records'?'replace':'append',days:{},cells:{}}});setNotice('Confira o resumo, cada data e os campos antes de aplicar. A gravação será feita no servidor.');};
 const run=async(mode)=>{setBusy(true);setNotice('');setPreview(null);const controller=new AbortController();abort.current=controller;try{const captured=await capture();if(mode==='records')prepare(organizeFromRecords(bed,captured.token),captured,'records');else {const r=await requestClinicalAI('organize_chart',[bed],{text,signal:controller.signal});if(!controller.signal.aborted)prepare(r.chart,captured,'claude');}}catch(e){if(!controller.signal.aborted)setNotice(e.message);}finally{if(!controller.signal.aborted)setBusy(false);}};
 const patchDoc=fn=>setPreview(p=>({...p,document:fn(p.document)}));
 const editDay=(index,fn)=>patchDoc(doc=>({...doc,dias:doc.dias.map((d,i)=>i===index?fn(d):d)}));
 const selectChoice=(group,key,value)=>setPreview(p=>({...p,choices:{...p.choices,[group]:group==='summary'?value:{...p.choices[group],[key]:value}}}));
 const apply=async()=>{setBusy(true);try{const captured=await capture();if(captured.source!==preview.source||captured.version!==preview.version||captured.token!==preview.document.review_token)throw Error('Os registros mudaram. Gere novamente antes de aplicar.');const document=validateChart(preview.document,bed);const accepted=actions.importChart(bed.bedId,document,preview.choices,{source:preview.origin,sourceText:preview.sourceText},preview.version);if(accepted){setPreview(null);setResponse('');setNotice('Organização enviada para salvamento. Confira a indicação Salvo no servidor.');}}catch(e){setPreview(null);setNotice(e.message);}finally{setBusy(false);}};
 const records=mergeDailyRecords(bed);
 return <section className="overview-block no-print chart-organizer"><div className="section-heading"><h2>Resumo e organização da internação</h2>{bed.hospitalizationSummary&&<button className="secondary-btn" onClick={async()=>{try{await copyText(bed.hospitalizationSummary.texto);setNotice('Resumo copiado.');}catch(e){setNotice(e.message);}}}>Copiar resumo da internação</button>}</div>
 {bed.hospitalizationSummary?.texto&&<><div className="clinical-grid">{Object.entries(SUMMARY_SECTIONS).filter(([k])=>bed.hospitalizationSummary.sections?.[k]).map(([k,label])=><section className="clinical-card clinical-wide" key={k}><h3>{label}</h3><p style={{whiteSpace:'pre-wrap'}}>{bed.hospitalizationSummary.sections[k]}</p></section>)}</div><p className="muted">{(bed.hospitalizationSummaryRevisions||[]).length} versão(ões) do resumo · {bed.hospitalizationSummary.author} · {new Date(bed.hospitalizationSummary.savedAt).toLocaleString('pt-BR')}</p>{bed.hospitalizationSummaryRevisions?.length>1&&<details><summary>Histórico dos resumos</summary>{bed.hospitalizationSummaryRevisions.slice(0,-1).reverse().map((v,i)=><article className="daily-revision" key={i}><strong>{new Date(v.savedAt).toLocaleString('pt-BR')}</strong><pre>{v.texto}</pre></article>)}</details>}</>}
 <details><summary className="text-btn">Organizar prontuário / importar resumo e evoluções</summary><p className="muted">O resumo reúne toda a internação. As evoluções, fichas e passagens são distribuídas pela data assistencial. Sem API, reúna os registros já salvos ou copie o prompt para uma IA externa e cole o JSON retornado abaixo.</p>
 <label>Documentação adicional desta internação<textarea aria-label="Documentação adicional desta internação" rows={7} maxLength={120000} value={text} disabled={busy||!!state.reviewEpisodeId} onChange={e=>{setText(e.target.value);setPreview(null);}} placeholder="Cole resumo de internação, evoluções de vários dias ou outros registros. Preserve as datas e confira se todos pertencem a este paciente."/></label>
 <div className="editor-actions"><button className="secondary-btn" disabled={!ready} onClick={()=>run('records')}>Reunir todos os dias dos registros</button><button className="primary-btn" disabled={!ready} onClick={()=>run('ai')}>{busy?'Organizando…':'Organizar prontuário com IA'}</button><button className="secondary-btn" disabled={!ready} onClick={async()=>{try{const c=await capture();await copyText(chartPrompt(bed,c.token,text));setNotice('Prompt copiado com os registros desta internação. Envie-o à IA externa autorizada e cole o JSON retornado abaixo.');}catch(e){setNotice(e.message);}}}>Copiar prompt de organização</button>{busy&&<button className="secondary-btn" onClick={()=>{abort.current?.abort();setBusy(false);}}>Cancelar</button>}</div>
 {!ready&&!busy&&<p className="muted">{state.reviewEpisodeId?'Internação arquivada em consulta. Restaure para editar.':'Aguarde a confirmação do salvamento antes de gerar ou aplicar.'}</p>}
 <label>Resposta de organização (JSON)<textarea aria-label="Resposta de organização (JSON)" rows={6} value={response} disabled={busy||!!state.reviewEpisodeId} onChange={e=>{setResponse(e.target.value);setPreview(null);}} placeholder="JSON puro ou dentro de uma caixa de código Markdown"/></label>
 <div className="editor-actions"><button className="secondary-btn" disabled={!ready||!response.trim()} onClick={async()=>{try{prepare(response,await capture(),'external');}catch(e){setPreview(null);setNotice(e.message);}}}>Revisar organização recebida</button><button className="secondary-btn" disabled={busy} onClick={()=>{setResponse('');setPreview(null);setNotice('');}}>Limpar resposta de organização</button></div>
 {preview&&<div className="chart-review"><h3>Revisar resumo e registros por data</h3><p>{preview.document.nome} · Leito {preview.document.leito} · {preview.document.dias.length} dia(s) para importar</p>
 <label>Resumo existente<select aria-label="Tratamento do resumo existente" value={preview.choices.summary} onChange={e=>selectChoice('summary',null,e.target.value)}><option value="append">Complementar preservando o texto existente</option><option value="keep">Manter os campos já preenchidos</option><option value="replace">Substituir campos revisados e guardar versão anterior</option></select></label>
 {Object.entries(SUMMARY_SECTIONS).map(([k,label])=><label key={k}>{label}<textarea aria-label={'Resumo · '+label} rows={k==='curso_clinico'?6:3} value={preview.document.resumo_internacao[k]} onChange={e=>{const value=e.target.value;patchDoc(doc=>({...doc,resumo_internacao:{...doc.resumo_internacao,[k]:value}}));}}/></label>)}
 {preview.document.dias.map((day,index)=><details key={day.data} className="daily-revision"><summary>{isoToBR(day.data)} · evolução, ficha e passagem</summary>{records[day.data]?.evolution?.texto&&<><details><summary>Evolução já salva nesta data</summary><pre>{records[day.data].evolution.texto}</pre></details><label>Evolução existente<select aria-label={'Tratamento da evolução '+day.data} value={preview.choices.days[day.data]||'append'} onChange={e=>selectChoice('days',day.data,e.target.value)}><option value="append">Complementar as seções existentes</option><option value="keep">Manter a evolução existente</option><option value="replace">Substituir texto revisado e guardar versão anterior</option></select></label></>}
 {Object.entries(DAY_SECTIONS).map(([k,label])=><label key={k}>{label}<textarea aria-label={day.data+' · '+label} rows={3} value={day.secoes[k]} onChange={e=>{const value=e.target.value;editDay(index,d=>({...d,secoes:{...d.secoes,[k]:value}}));}}/></label>)}
 {day.ficha.length>0&&<><h4>Valores da ficha · {isoToBR(day.data)}</h4><p className="muted">Controles: 07:00 do dia anterior às 07:00 desta data.</p>{day.ficha.map((c,i)=>{const previous=records[day.data]?.cells?.[c.row+':'+c.slot]||'';return <div key={c.row+':'+c.slot}><label>{mobileLabel(c.row,c.slot)}<input aria-label={day.data+' · ficha '+c.row+':'+c.slot} value={c.value} maxLength={300} onChange={e=>{const value=e.target.value;editDay(index,d=>({...d,ficha:d.ficha.map((cell,j)=>j===i?{...cell,value}:cell)}));}}/></label>{previous&&previous!==c.value&&<label>Valor existente: {previous}<select aria-label={'Conflito '+day.data+' '+c.row+':'+c.slot} value={preview.choices.cells[day.data+':'+c.row+':'+c.slot]||'keep'} onChange={e=>selectChoice('cells',day.data+':'+c.row+':'+c.slot,e.target.value)}><option value="keep">Manter valor existente</option><option value="replace">Aplicar valor revisado</option></select></label>}</div>;})}</>}
 <h4>Passagem deste dia</h4><p className="muted">As seções de diagnósticos, antecedentes, história, condutas e pendências também alimentam a passagem. Itens existentes e checklist serão preservados.</p>{CHART_HANDOFF.map((k,i)=><label key={k}>{handoffLabels[i]}<textarea aria-label={day.data+' · passagem '+k} rows={2} value={day.passagem[k].join('\n')} onChange={e=>{const value=e.target.value.split('\n').filter(v=>v.trim());editDay(index,d=>({...d,passagem:{...d.passagem,[k]:value}}));}}/></label>)}</details>)}
 <p className="muted">Campos vazios não apagam registros. Datas fora da folha atual continuam no histórico; a ficha mantém seis colunas por folha. A evolução mais recente permanece a referência atual. Nenhuma prescrição será alterada.</p><button className="primary-btn" disabled={!ready} onClick={apply}>Aplicar organização revisada</button><button className="secondary-btn" onClick={()=>setPreview(null)}>Descartar revisão</button></div>}
 </details>{notice&&<p role="status" className="inline-notice">{notice}</p>}</section>;
}
