import React,{useState,useEffect} from 'react';
import {dailyDates,mergeDailyRecords} from '../core/dailyHistory.js';
import {FICHA_ROWS,slotsOf,mobileLabel,isoToBR,todayISO,stayDays} from '../core/icuStore.js';
import {splitClinicalText} from '../services/textEvolution.js';
export default function PatientDailyPanel({bed,onRegister}) {
 const records=mergeDailyRecords(bed),dates=dailyDates(bed,todayISO());
 const observed=dates.filter(d=>Object.keys(records[d]?.cells||{}).length||records[d]?.evolution);
 const initial=observed.filter(d=>d<=todayISO()).at(-1)||dates.filter(d=>d<=todayISO()).at(-1)||dates.at(-1)||'';
 const [selected,setSelected]=useState(initial),[range,setRange]=useState('6');
 useEffect(()=>setSelected(initial),[bed.bedId,bed.patientId,bed.episodeId]);
 if(!dates.length)return <section className="overview-block no-print"><h2>Acompanhamento diário</h2><p className="muted">Informe a data de internação ou registre uma data na ficha para iniciar o painel.</p></section>;
 const date=dates.includes(selected)?selected:initial,record=records[date]||{cells:{}},cells=record.cells||{},position=dates.indexOf(date);
 const viewDates=range==='all'?dates:dates.slice(Math.max(0,position-5),position+1);
 const summaries=[['PAM',13],['Frequência cardíaca',14],['Temperatura',16],['Diurese',7],['Balanço hídrico',12],['Creatinina',44]];
 return <div className="daily-panel no-print"><section className="overview-block"><div className="section-heading"><div><span className="eyebrow">ACOMPANHAMENTO DA INTERNAÇÃO</span><h2>Painel diário</h2></div><label>Dia da internação<select aria-label="Dia da internação" value={date} onChange={e=>setSelected(e.target.value)}>{dates.map(d=><option key={d} value={d}>{isoToBR(d)}{bed.hospitalAdmissionDate||bed.admissionDate?` · D${stayDays(bed.hospitalAdmissionDate||bed.admissionDate,d)}`:''}{!Object.keys(records[d]?.cells||{}).length&&!records[d]?.evolution?' · sem registro':''}</option>)}</select></label></div><div className="daily-day-toolbar"><button className="secondary-btn" disabled={position===0} onClick={()=>setSelected(dates[position-1])}>Dia anterior</button><strong>{isoToBR(date)}</strong><button className="secondary-btn" disabled={position===dates.length-1} onClick={()=>setSelected(dates[position+1])}>Próximo dia</button></div>
 <div className="daily-timeline" aria-label="Linha do tempo diária">{dates.map(d=>{const registered=!!Object.keys(records[d]?.cells||{}).length||!!records[d]?.evolution;return <button key={d} aria-pressed={d===date} onClick={()=>setSelected(d)}><strong>{isoToBR(d).slice(0,5)}</strong><small>{registered?'Registrado':d>todayISO()?'Data futura':'Sem registro'}</small></button>;})}</div>
 <div className="daily-summary-grid">{summaries.map(([label,row])=><section key={label}><span>{label}</span><strong>{row===44?cells['44:0']||'':slotsOf(row).map(s=>cells[`${row}:${s}`]||'').join(' / ')}</strong>{FICHA_ROWS[row].kind==='pair'&&row!==44&&<small>mínimo / máximo</small>}</section>)}</div>
 <div className="section-heading"><h3>Evolução médica · {isoToBR(date)}</h3><button className="primary-btn" onClick={()=>onRegister(date)}>Registrar evolução deste dia</button></div>{record.evolution?.texto?<><div className="clinical-grid">{splitClinicalText(record.evolution.texto).map((section,i)=><section key={i} className={`clinical-card ${section.lines.join('').length>450?'clinical-wide':''}`}><h3>{section.title}</h3><div>{section.lines.map((line,j)=><p key={j}>{line}</p>)}</div></section>)}</div><p className="muted">Registro salvo em {new Date(record.evolution.editadoEm||record.evolution.geradoEm).toLocaleString('pt-BR')}. {(record.evolutionRevisions||[]).length} versão(ões) salva(s) para esta data.</p>{(record.evolutionRevisions||[]).length>1&&<details><summary>Versões anteriores deste dia</summary>{record.evolutionRevisions.slice(0,-1).reverse().map((revision,i)=><article className="daily-revision" key={i}><strong>{new Date(revision.savedAt).toLocaleString('pt-BR')}</strong><pre>{revision.texto}</pre></article>)}</details>}</>:<p className="muted">Nenhuma evolução registrada para esta data.</p>}
 </section>
 <section className="overview-block"><div className="section-heading"><h2>Comparação por data</h2><label>Período<select aria-label="Período das comparações" value={range} onChange={e=>setRange(e.target.value)}><option value="6">Até seis dias até o selecionado</option><option value="all">Todos os dias da internação</option></select></label></div><p className="muted">Valores transcritos, sem conversão de unidades. Sinais vitais e balanço hídrico: 07:00 do dia anterior às 07:00 da data de fechamento.</p>
 <Comparison title="Sinais vitais" rows={[13,14,15,16,17,18]} dates={viewDates} records={records}/><Comparison title="Ganhos, perdas e balanço hídrico" rows={[3,4,7,8,9,10,12]} dates={viewDates} records={records}/><Comparison title="Exames laboratoriais e gasometria" rows={Array.from({length:21},(_,i)=>i+34)} dates={viewDates} records={records}/><Comparison title="Suporte, dispositivos e medicações" rows={[0,1,2,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33]} dates={viewDates} records={records}/>
 </section></div>;
}
function Comparison({title,rows,dates,records}) {
 return <section className="daily-comparison"><h3>{title}</h3><div className="trends-scroll"><table><thead><tr><th>Parâmetro</th>{dates.map(date=><th key={date}>{isoToBR(date)}</th>)}</tr></thead><tbody>{rows.flatMap(row=>slotsOf(row).map(slot=><tr key={`${row}:${slot}`}><th>{FICHA_ROWS[row].section} · {mobileLabel(row,slot)}</th>{dates.map(date=><td key={date}>{records[date]?.cells?.[`${row}:${slot}`]||''}</td>)}</tr>))}</tbody></table></div></section>;
}
