import assert from 'node:assert/strict';
import {A,createInitialState,icuReducer,referenceDay,hydrate,saveState,todayISO,addDaysISO,deriveHandoff,censusOf} from './app/pep/core/icuStore.js';
import {buildClinicalXML} from './app/pep/services/evolucaoSchema.js';
import {evolutionFromText,splitClinicalText} from './app/pep/services/textEvolution.js';
let state=createInitialState();
state=icuReducer(state,{type:A.UPDATE_BED,bedId:'01',patch:{patientName:'PACIENTE TESTE'}});
assert.equal(state.beds['01'].status,'occupied');
state=icuReducer(state,{type:A.SET_DATE,bedId:'01',day:0,value:todayISO(),cascade:true});
assert.equal(state.beds['01'].dates[5],addDaysISO(todayISO(),5));
state=icuReducer(state,{type:A.SET_CELL,bedId:'01',day:0,row:45,slot:0,value:'2,3'});
assert.equal(referenceDay(state.beds['01']),0,'Datas futuras não devem definir a referência');
assert.match(buildClinicalXML(state.beds['01']),/D-0.*coluna="D1"/);
assert.match(buildClinicalXML(state.beds['01']),/2,3/);
assert.equal(saveState(state,null),false);
const old=hydrate({beds:{'01':{patientName:'LEGADO',status:'occupied',handoff:{diagnosticos:['Hipótese documentada']}}}});
assert.doesNotThrow(()=>deriveHandoff(old.beds['01']));
const text='# DIAGNÓSTICOS / HIPÓTESES\n- Hipótese documentada\n# EXAME FÍSICO\nAchado registrado pelo médico\n# PLANO DO DIA / CONDUTAS\n- Conduta registrada\n# METAS E PENDÊNCIAS\n- Ação pendente';
const evo=evolutionFromText(text);
assert.equal(evo.texto,text);
assert.deepEqual(evo.payload.diagnosticos_atuais,['Hipótese documentada']);
assert.deepEqual(evo.payload.condutas,['Conduta registrada']);
assert.deepEqual(evo.payload.pendencias,['Ação pendente']);
assert.equal(splitClinicalText(text).length,4);
state=icuReducer(state,{type:A.SET_EVOLUCAO,bedId:'01',evolucao:evo});
assert.deepEqual(deriveHandoff(state.beds['01']).condutas,['Conduta registrada']);
assert.equal(deriveHandoff(state.beds['02']).condutas.length,0);
state=icuReducer(state,{type:A.SET_STATUS,bedId:'01',status:'critical'});
state=icuReducer(state,{type:A.UPDATE_BED,bedId:'01',patch:{isIsolation:true}});
assert.equal(censusOf(state).critical,1);assert.equal(censusOf(state).isolation,1);
const roundtrip=hydrate(JSON.parse(JSON.stringify(state)));
assert.equal(roundtrip.beds['01'].evolucao.texto,text);
console.log('PASS: admissão, referência temporal, XML, armazenamento, migração, texto, passagem e isolamento entre leitos.');
