import assert from 'node:assert/strict';
import {calculate,rate,clearance,prescriptionText} from './app/pep/core/prescricao.js';
import {readFileSync} from 'node:fs';
import {A,createInitialState,icuReducer,hydrate} from './app/pep/core/icuStore.js';
const meds=JSON.parse(readFileSync(new URL('./app/pep/core/medicamentos.json',import.meta.url)));
assert.equal(meds.length,87);
const nor=meds.find(m=>m.nome.startsWith('Norepinefrina'));
const r=calculate(nor,'0,1','70');assert.deepEqual(r.rates,[1.96875,6.5625,39.375]);
assert.equal(prescriptionText(nor,r,70),nor.prescricao+' # Iniciar com 6,5625 mL/h #');
const dex=meds.find(m=>m.nome.includes('Dexmedetomidina'));assert.equal(dex.unidade,'mcg/kg/h');assert.deepEqual(calculate(dex,.4,70).rates,[3.5,7,12.25]);
assert.equal(rate(1,'mg/kg/h',70,1000,'mcg/mL'),70);
assert.equal(rate(1,'mcg/kg/min',70,1,'mg/mL'),4.2);
assert.equal(rate(2,'UI/h','',10,'UI/mL'),.2);
assert.throws(()=>rate(1,'UI/h',70,1,'mg/mL'),/UI não/);
for(const weight of ['',0,-70,'70kg','70.0.0'])assert.throws(()=>calculate(nor,.1,weight));
for(const desired of [0,-1,'2x','',.01,.61])assert.throws(()=>calculate(nor,desired,70));
assert.throws(()=>rate(1,'mcg/kg/min',70,0,'mcg/mL'));
assert.throws(()=>rate(1,'mcg/kg/seg',70,1,'mcg/mL'));
assert.equal(clearance(70,70,1,'M'),68.05555555555556);assert.throws(()=>clearance(70,70,1,''));assert.throws(()=>clearance(12,70,1,'M'));
let state=createInitialState();state=icuReducer(state,{type:A.SAVE_MEDICATION,medication:{...nor,nome:'Modelo ajustado'}});state=icuReducer(state,{type:A.UPDATE_BED,bedId:'01',patch:{prescriptions:[{text:'Teste'}]}});const restored=hydrate(JSON.parse(JSON.stringify(state)));assert.equal(restored.customMedications[0].nome,'Modelo ajustado');assert.equal(restored.beds['01'].prescriptions[0].text,'Teste');assert.equal(restored.beds['02'].prescriptions,undefined);
console.log('PASS: catálogo, dose inicial/desejada/máxima, conversão de unidades, dexmedetomidina, limites, entradas inválidas, função renal e backup.');
