import React,{useMemo,useState,useEffect} from 'react';
import {useICU,useBed} from '../context/ICUContext.jsx';
import catalog from '../core/medicamentos.json';
import {UNITS,calculate,prescriptionText,clearance,fmt,copyText} from '../core/prescricao.js';
import {printDocument} from '../print/printDocument.js';
import {isoToBR,todayISO} from '../core/icuStore.js';
const EMPTY={nome:'',categoria:'Outros',prescricao:'',calc_peso:false,unidade:'mcg/kg/min',dose_min:'',dose_max:'',concentracao:'',unidade_conc:'mcg/mL'};
export default function Prescricao({onGoBeds}) {
 const {state,actions}=useICU();const {bed,update}=useBed();
 const [query,setQuery]=useState(''),[category,setCategory]=useState('Todas'),[draft,setDraft]=useState(null),[desired,setDesired]=useState(''),[checked,setChecked]=useState(false),[instructions,setInstructions]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{setDraft(null);setDesired('');setChecked(false);setInstructions('');setNotice('');},[bed.patientId,bed.episodeId]);
 const medications=useMemo(()=>{const migrated=(state.legacyCatalog||[]).map(m=>({id:'legacy-custom-'+m.id,nome:m.name,categoria:'Catálogo anterior',prescricao:m.text,calc_peso:!!m.weight_based,unidade:m.formula||'',dose_min:m.min_dose??'',dose_max:m.max_dose??'',concentracao:m.concentration??'',unidade_conc:m.concentration_unit||'',pendencia:'Modelo anterior: confira indicação, dose, unidades e diluição antes de utilizar.',obs:m.notes||''}));const custom=[...migrated,...(state.customMedications||[])];return [...catalog.filter(m=>!custom.some(c=>c.id===m.id)),...custom].sort((a,b)=>a.nome.localeCompare(b.nome,'pt-BR'));},[state.customMedications,state.legacyCatalog]);
 const filtered=medications.filter(m=>(category==='Todas'||m.categoria===category)&&`${m.nome} ${m.prescricao}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')));
 const list=Array.isArray(bed.prescriptions)?bed.prescriptions:[];
 const set=(k,v)=>{setDraft(d=>({...d,[k]:v}));setChecked(false);};
 const choose=m=>{setDraft({...m});setDesired('');setInstructions('');setChecked(false);setNotice('');};
 let result=null,error='',text='';
 if(draft){try{
  if(draft.pendencia&&!checked)throw new Error(draft.pendencia);
  if(!draft.nome.trim())throw new Error('Preencha o nome do medicamento.');
  result=draft.calc_peso?calculate(draft,desired,bed.weight.value):null;
  if(!draft.calc_peso&&!instructions.trim())throw new Error('Complete as instruções da prescrição: dose, via e intervalo/duração.');
  text=prescriptionText(draft,result,bed.weight.value)+(instructions.trim()?`\n${instructions.trim()}`:'');

 }catch(e){error=e.message;}}
 let crcl=null,renalError='';try{if(bed.creatinine)crcl=clearance(bed.age,bed.weight.value,bed.creatinine,bed.sex);}catch(e){renalError=e.message;}
 const copy=async value=>{try{await copyText(value);setNotice('Texto copiado.');}catch(e){setNotice(e.message);}};
 const saveModel=()=>{if(!draft.nome.trim()||!draft.prescricao.trim()){setNotice('Preencha nome e receita.');return;}if(draft.pendencia&&!checked){setNotice('Resolva a inconsistência antes de salvar o modelo.');return;}const m={...draft,id:draft.id||`local-${Date.now()}`};if(checked)delete m.pendencia;actions.saveMedication(m);setDraft(m);setNotice('Modelo salvo no catálogo compartilhado e incluído no backup.');};
 if(bed.status==='empty')return <div className="empty-state"><h2>Selecione um paciente</h2><p>Admita um paciente para vincular peso e prescrições ao leito.</p><button className="primary-btn" onClick={onGoBeds}>Mapa de leitos</button></div>;
 return <><div className="rx-workspace no-print">
 <section className="editor-card"><div className="section-heading"><div><span className="eyebrow">EV · BOMBA DE INFUSÃO CONTÍNUA</span><h2>Prescrição e diluições</h2></div><button className="secondary-btn" onClick={()=>{choose({...EMPTY});}}>Novo modelo</button></div><p className="muted">Catálogo EV BIC Rodolfo: {catalog.length} modelos. As faixas cadastradas são referências; ajuste-as ao protocolo e à indicação. Dose inicial significa início da infusão contínua, sem bolus.</p><div className="rx-fields"><Field label="Peso de cálculo (kg)" value={bed.weight.value} onChange={v=>update({weight:{...bed.weight,value:v}})}/><label>Sexo (Cockcroft–Gault)<select value={bed.sex||''} onChange={e=>update({sex:e.target.value})}><option value="">Selecionar</option><option value="M">Masculino</option><option value="F">Feminino</option></select></label><Field label="Creatinina (mg/dL)" value={bed.creatinine||''} onChange={v=>update({creatinine:v})}/></div><label className="rx-check"><input type="checkbox" checked={bed.weight.isEstimated} onChange={e=>update({weight:{...bed.weight,isEstimated:e.target.checked}})}/>Peso estimado</label>{crcl!==null&&<p className="inline-notice">ClCr estimado: {fmt(crcl)} mL/min · Cockcroft–Gault · {bed.age} anos. Estimativa não apropriada para função renal instável ou diálise; peso e método devem ser definidos pelo prescritor.</p>}{renalError&&<p className="rx-error">{renalError}</p>}</section>
 <div className="rx-columns"><aside className="editor-card rx-catalog"><label>Buscar medicamento<input type="search" placeholder="Nome ou diluição" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Categoria<select value={category} onChange={e=>setCategory(e.target.value)}>{['Todas',...new Set(medications.map(m=>m.categoria))].map(c=><option key={c}>{c}</option>)}</select></label><p className="muted">{filtered.length} modelos</p><div className="rx-list">{filtered.map(m=><button key={m.id} aria-pressed={draft?.id===m.id} onClick={()=>choose(m)}><strong>{m.nome}</strong><small>{m.categoria} · {m.calc_peso?'Cálculo BIC':'Texto de diluição'}</small></button>)}</div>{!filtered.length&&<p>Nenhum modelo encontrado.</p>}</aside>
 <section className="editor-card rx-editor">{draft?<><h2>{draft.nome||'Novo modelo'}</h2>{draft.nota&&<p className="inline-notice">{draft.nota} {draft.fonte&&<a href={draft.fonte} target="_blank" rel="noreferrer">Consultar bula</a>}</p>}<details><summary>Editar receita e parâmetros</summary><div className="rx-fields"><Field label="Nome do medicamento" value={draft.nome} onChange={v=>set('nome',v)}/><label>Categoria<select value={draft.categoria} onChange={e=>set('categoria',e.target.value)}>{['Antibióticos','Outros','Vasoativos e Sedação'].map(c=><option key={c}>{c}</option>)}</select></label></div><label className="rx-check"><input type="checkbox" checked={draft.calc_peso} onChange={e=>set('calc_peso',e.target.checked)}/>Calcular infusão contínua</label></details>
 <label>Receita e diluição<textarea rows="4" value={draft.prescricao} onChange={e=>set('prescricao',e.target.value)}/></label>{draft.calc_peso&&<><div className="rx-fields"><Field label="Dose inicial da infusão" value={draft.dose_min} onChange={v=>set('dose_min',v)}/><Field label="Dose máxima cadastrada" value={draft.dose_max} onChange={v=>set('dose_max',v)}/><label>Unidade de dose<select value={draft.unidade} onChange={e=>set('unidade',e.target.value)}>{UNITS.map(u=><option key={u}>{u}</option>)}</select></label><Field label="Concentração final da solução" value={draft.concentracao} onChange={v=>set('concentracao',v)}/><label>Unidade da concentração<select value={draft.unidade_conc} onChange={e=>set('unidade_conc',e.target.value)}>{['mcg/mL','mg/mL','UI/mL'].map(u=><option key={u}>{u}</option>)}</select></label><Field label={`Dose desejada (${draft.unidade})`} value={desired} onChange={setDesired}/></div><p className="muted">Informe a concentração após diluição, considerando o volume final (medicamento + diluente). O cálculo não deduz a concentração do texto.</p></>}
 {draft.pendencia&&<div className="rx-problem"><p>{draft.pendencia}</p><label className="rx-check"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>Conferi a apresentação disponível, a modalidade e a concentração; os campos acima refletem a receita corrigida.</label></div>}
 <label>{draft.calc_peso?'Orientações adicionais (opcional)':'Instruções da prescrição (dose, via e intervalo/duração)'}<textarea rows="2" value={instructions} onChange={e=>setInstructions(e.target.value)}/></label>{!!draft.ajuste_renal?.length&&<details className="rx-renal"><summary>Ajustes renais do catálogo original</summary><p>Referências importadas, sem validação de indicação e esquema. Não são adicionadas automaticamente ao texto. Registre o ajuste escolhido nas instruções após conferir o protocolo, especialmente em lesão renal aguda e diálise.</p><ul>{draft.ajuste_renal.map((r,i)=><li key={i}>{r.texto}</li>)}</ul></details>}
 {result&&<div className="rx-rates">{['Inicial','Desejada','Máxima cadastrada'].map((l,i)=><div key={l}><small>{l}</small><strong>{fmt(result.rates[i])} <span>mL/h</span></strong><small>{fmt([result.initial,result.target,result.max][i])} {draft.unidade}</small></div>)}</div>}{error&&<p role="status" className="rx-error">{error}</p>}<label>Texto para copiar<textarea className="rx-output" rows="9" readOnly value={text}/></label><div className="rx-actions"><button className="primary-btn" disabled={!text} onClick={()=>copy(text)}>Copiar prescrição</button><button className="secondary-btn" disabled={!text} onClick={()=>{update({prescriptions:[...list,{id:`rx-${Date.now()}`,name:draft.nome,text,createdAt:new Date().toISOString(),medication:{...draft},desired,weight:bed.weight.value,calculation:result?{...result}:null,clinicalDate:todayISO()}]});setNotice('Prescrição adicionada ao paciente.');}}>Adicionar ao paciente</button><button className="text-btn" onClick={saveModel}>Salvar modelo no catálogo</button></div></>:<div className="empty-state compact"><h2>Selecione um medicamento</h2><p>Confira a receita, informe a dose desejada e veja a conversão em mL/h.</p></div>}</section></div>
 {notice&&<p role="status" className="inline-notice">{notice}</p>}<section className="editor-card"><div className="section-heading"><h2>Prescrições do paciente · {list.length}</h2><div className="rx-actions"><button className="secondary-btn" disabled={!list.length} onClick={()=>copy(list.map((x,i)=>`${i+1}. ${x.text}`).join('\n\n'))}>Copiar todas</button><button className="primary-btn" disabled={!list.length} onClick={()=>printDocument('prescricao')}>Imprimir prescrições</button></div></div><p className="muted">Cada item conserva os parâmetros da inclusão. Após alterar peso ou diluição, recalcule e substitua o item.</p>{list.map((x,i)=><article className="rx-saved" key={x.id}><div><strong>{i+1}. {x.name}</strong><button className="text-btn" onClick={()=>update({prescriptions:list.filter(y=>y.id!==x.id)})}>Remover</button></div><pre>{x.text}</pre></article>)}{!list.length&&<p className="muted">Nenhuma prescrição adicionada.</p>}</section></div>
 <div id="print-prescricao" className="hidden print:block rx-print"><h1>HOSPITAL REGIONAL DE IVAIPORÃ</h1><h2>Prescrição · UTI Adulto</h2><p>Paciente: {bed.patientName} · Leito: {bed.bedId} · {isoToBR(todayISO())}</p>{list.map((x,i)=><section key={x.id}><h3>{i+1}. {x.name}</h3><pre>{x.text}</pre></section>)}<footer>Prescritor: __________________________________ CRM: __________ Horário: __________</footer></div></>;
}
function Field({label,value,onChange}) {return <label>{label}<input inputMode={/dose|peso|concentra|creatinina/i.test(label)?'decimal':'text'} value={value??''} onChange={e=>onChange(e.target.value)}/></label>;}
