import assert from'node:assert/strict';import fs from'node:fs';import http from'node:http';import{DatabaseSync}from'node:sqlite';import{build}from'esbuild';
const{chromium}=await import(process.env.PEP_PLAYWRIGHT_MODULE||'/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.mjs');
fs.mkdirSync('.sites-runtime/print-tests',{recursive:true});
await build({stdin:{contents:"import React from 'react';import{createRoot}from'react-dom/client';import App from './app/pep/App.jsx';createRoot(document.getElementById('root')).render(<App/>);",resolveDir:process.cwd(),loader:'jsx'},bundle:true,platform:'browser',format:'iife',loader:{'.css':'empty'},outfile:'.sites-runtime/ui-test.js'});
await build({entryPoints:['worker/pep-api.ts'],bundle:true,platform:'node',format:'esm',outfile:'.sites-runtime/ui-api.mjs'});const{handlePepApi}=await import('../.sites-runtime/ui-api.mjs');
const sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));
const prepare=text=>{let args=[];return {text,bind(...a){args=a;return this},async first(){return sql.prepare(text).get(...args)||null},async all(){return {results:sql.prepare(text).all(...args)}},async run(){const r=sql.prepare(text).run(...args);return {meta:{changes:Number(r.changes)}}}}};
const db={prepare,async batch(items){sql.exec('BEGIN');try{const out=[];for(const s of items)out.push(await s.run());sql.exec('COMMIT');return out}catch(e){sql.exec('ROLLBACK');throw e}}};
for(let i=1;i<=10;i++){const id='synthetic-'+i,bed=String(i).padStart(2,'0');sql.prepare('INSERT INTO patients(id,bed,name,age,admission_at,icu_admission_at,diagnoses,medical_history,summary)VALUES(?,?,?,?,?,?,?,?,?)').run(id,bed,'PACIENTE SINTÉTICO '+i,'50','2026-09-20','2026-09-20','DIAGNÓSTICO DOCUMENTADO','ANTECEDENTE DOCUMENTADO','HISTÓRIA DOCUMENTADA');const data={patient:'PACIENTE SINTÉTICO '+i,bed,admission:'2026-09-20',dates:['20/09/2026','21/09/2026','22/09/2026','23/09/2026','24/09/2026','25/09/2026','26/09/2026','27/09/2026'],cells:{'7:7:0':'1000','7:44:0':'1,2'}};sql.prepare('INSERT INTO daily_sheets(patient_id,admission,data,version,updated_at,author)VALUES(?,?,?,?,?,?)').run(id,'2026-09-20',JSON.stringify(data),1,'2026-09-30T10:00:00Z','AUTOR SINTÉTICO');sql.prepare('INSERT INTO evolutions(patient_id,evolution_date,text)VALUES(?,?,?)').run(id,'2026-09-27','# HMP:\nANTECEDENTE DOCUMENTADO\n# HMA:\nHISTÓRIA DOCUMENTADA\n# CONDUTAS:\nPLANO DOCUMENTADO\n# PENDÊNCIAS:\nPENDÊNCIA DOCUMENTADA');}
const css=fs.readdirSync('dist/client/assets').filter(f=>f.endsWith('.css')).map(f=>fs.readFileSync('dist/client/assets/'+f,'utf8')).join('\n');
const faults={dropNext:false};
const server=http.createServer(async(req,res)=>{try{if(req.url.startsWith('/api/pep')){let raw='';for await(const chunk of req)raw+=chunk;const response=await handlePepApi(new Request('http://localhost'+req.url,{method:req.method,...(req.method==='POST'?{body:raw}: {})}),db);if(req.method==='POST'&&response.ok&&faults.dropNext){faults.dropNext=false;res.writeHead(504,{'Content-Type':'application/json'});res.end(JSON.stringify({error:'Timeout sintético após commit'}));return;}res.writeHead(response.status,{'Content-Type':'application/json'});res.end(await response.text());}else if(req.url==='/ui.js'){res.setHeader('Content-Type','text/javascript; charset=utf-8');res.end(fs.readFileSync('.sites-runtime/ui-test.js'));}else{res.setHeader('Content-Type','text/html; charset=utf-8');res.end('<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>'+css+'</style></head><body><div id="root"></div><script src="/ui.js"></script></body></html>');}}catch(e){res.statusCode=500;res.end(String(e));}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({executablePath:process.env.PEP_CHROMIUM_EXECUTABLE||'/tmp/pep-pdf-browser/executable/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-zygote']});const results={};
try{for(const [name,width,height]of[['desktop',1440,1000],['mobile',390,844]]){const page=await browser.newPage({viewport:{width,height}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);await page.getByRole('heading',{name:'Mapa de leitos',exact:true}).waitFor({timeout:7000}).catch(async e=>{console.log(JSON.stringify({errors,body:await page.locator('body').innerText()}));throw e;});await page.getByText('PACIENTE SINTÉTICO 1',{exact:true}).waitFor();await page.screenshot({path:'.sites-runtime/print-tests/ui-'+name+'.png',fullPage:true});results[name]={errors,scrollWidth:await page.evaluate(()=>document.documentElement.scrollWidth),width,bedCards:await page.locator('.bed-card').count()};
 await page.getByRole('button',{name:'Abrir painel do leito 01'}).click();await page.getByRole('heading',{name:'Painel diário',exact:true}).waitFor();
 await page.getByText('Organizar prontuário / importar resumo e evoluções',{exact:true}).click();
 await page.evaluate(()=>{navigator.clipboard.writeText=async value=>{window.__copiedChartPrompt=value;};});await page.getByRole('button',{name:'Copiar prompt de organização',exact:true}).click();await page.getByText(/Prompt copiado com os registros desta internação/).waitFor();const copiedPrompt=await page.evaluate(()=>window.__copiedChartPrompt);assert.match(copiedPrompt,/CONTRATO JSON/);assert.match(copiedPrompt,/synthetic-1/);assert.match(copiedPrompt,/review_token/);results[name].chartPromptCopied=true;
 await page.getByRole('button',{name:'Reunir todos os dias dos registros',exact:true}).click();await page.getByRole('heading',{name:'Revisar resumo e registros por data',exact:true}).waitFor({timeout:5000});
 assert.match(await page.getByLabel('Resumo · Curso clínico da internação',{exact:true}).inputValue(),/2026-09-27/);
 await page.getByRole('button',{name:'Aplicar organização revisada',exact:true}).click();await page.getByText('Organização enviada para salvamento. Confira a indicação Salvo no servidor.',{exact:true}).waitFor();await page.getByRole('status').filter({hasText:/^Salvo no servidor$/}).waitFor();
 const {identityOf,chartToken,SUMMARY_SECTIONS,DAY_SECTIONS,CHART_HANDOFF}=await import('../app/pep/core/chartOrganization.js');const snapshot=await handlePepApi(new Request(origin+'/api/pep'),db).then(r=>r.json());const b=snapshot.state.beds['01'];
 const document={...identityOf(b,await chartToken(b)),resumo_internacao:{...Object.fromEntries(Object.keys(SUMMARY_SECTIONS).map(k=>[k,''])),historia_admissao:'RESUMO IMPORTADO REVISADO'},dias:Array.from({length:10},(_,i)=>({data:'2026-09-'+(20+i),secoes:{...Object.fromEntries(Object.keys(DAY_SECTIONS).map(k=>[k,''])),historia_intercorrencias:'REGISTRO DO DIA '+(20+i),condutas:'PLANO DO DIA '+(20+i)},ficha:[{row:44,slot:0,value:'1,9 mg/dL'}],passagem:Object.fromEntries(CHART_HANDOFF.map(k=>[k,[]]))}))};
 await page.getByLabel('Resposta de organização (JSON)',{exact:true}).fill(JSON.stringify({...document,episode_id:'OUTRO PACIENTE'}));await page.getByRole('button',{name:'Revisar organização recebida',exact:true}).click();await page.getByText(/Identificação ou internação divergente: episode_id/).waitFor();assert.equal(await page.getByRole('button',{name:'Aplicar organização revisada',exact:true}).count(),0);
 await page.getByLabel('Resposta de organização (JSON)',{exact:true}).fill('```json\n'+JSON.stringify(document)+'\n```');await page.getByRole('button',{name:'Revisar organização recebida',exact:true}).click();await page.getByRole('heading',{name:'Revisar resumo e registros por data',exact:true}).waitFor({timeout:5000});await page.getByLabel('Resumo · História da admissão',{exact:true}).fill('RESUMO EDITADO ANTES DE APLICAR');await page.getByRole('button',{name:'Aplicar organização revisada',exact:true}).click();await page.getByText('Organização enviada para salvamento. Confira a indicação Salvo no servidor.',{exact:true}).waitFor();await page.getByRole('status').filter({hasText:/^Salvo no servidor$/}).waitFor();
 await page.reload();await page.getByRole('button',{name:'Abrir painel do leito 01'}).click();await page.getByText('RESUMO EDITADO ANTES DE APLICAR',{exact:true}).waitFor();results[name].chartSummaryRecovered=true;results[name].chartPanelWidth=await page.evaluate(()=>document.documentElement.scrollWidth);assert.equal(results[name].chartPanelWidth,width);
 const persisted=await handlePepApi(new Request(origin+'/api/pep'),db).then(r=>r.json());assert.equal(persisted.state.beds['01'].dailyRecords['2026-09-29'].cells['44:0'],'1,9 mg/dL');assert.match(persisted.state.beds['01'].dailyRecords['2026-09-29'].evolution.texto,/REGISTRO DO DIA 29/);assert.ok(persisted.state.beds['01'].handoffByDate['2026-09-29'].condutas.includes('PLANO DO DIA 29'));
 results[name].dailyDates=await page.locator('.daily-timeline button').count();await page.getByRole('button',{name:'Preencher ficha',exact:true}).click();if(name==='desktop')faults.dropNext=true;await page.getByLabel('PERDAS · DIURESE · linha 7 · campo 1').fill('1234');if(name==='desktop'){await page.getByRole('button',{name:'Tentar salvar novamente'}).waitFor();await page.getByRole('button',{name:'Tentar salvar novamente'}).click();}await page.getByRole('status').filter({hasText:/^Salvo no servidor$/}).waitFor();await page.reload();await page.getByRole('button',{name:'Abrir painel do leito 01'}).click();await page.getByRole('button',{name:'Preencher ficha',exact:true}).click();results[name].reloadedValue=await page.getByLabel('PERDAS · DIURESE · linha 7 · campo 1').inputValue();
 await page.getByRole('navigation',{name:name==='mobile'?'Navegação móvel':'Principal'}).getByRole('button',{name:name==='mobile'?'Passagem':'Passagem de plantão'}).click();await page.getByRole('button',{name:'Gerar dos registros'}).click();await page.getByText('Revisão do preenchimento',{exact:true}).waitFor();results[name].handoffReview=await page.locator('.handoff-review article').count();await page.getByRole('button',{name:'Aplicar passagem revisada'}).click();await page.getByRole('status').filter({hasText:/^Salvo no servidor$/}).waitFor();await page.close();}
for(const value of Object.values(results)){assert.deepEqual(value.errors,[]);assert.equal(value.scrollWidth,value.width);assert.equal(value.bedCards,10);assert.ok(value.dailyDates>6);assert.equal(value.reloadedValue,'1234');assert.equal(value.handoffReview,10);assert.equal(value.chartSummaryRecovered,true);}
fs.writeFileSync('.sites-runtime/print-tests/ui-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results));}finally{await browser.close();server.close();}
