-- Esquema PostgreSQL equivalente às migrações SQLite 0000-0010 (drizzle/), com auditoria por gatilhos.
-- Datas continuam em texto ISO/SQLite para preservar o formato dos backups e do código cliente.

CREATE TABLE events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id text NOT NULL,
  occurred_at text NOT NULL,
  kind text NOT NULL DEFAULT 'clinico',
  text text NOT NULL,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE patients (
  id text PRIMARY KEY,
  bed text NOT NULL,
  name text NOT NULL,
  age text NOT NULL DEFAULT '',
  mrn text NOT NULL DEFAULT '',
  admission_at text NOT NULL DEFAULT '',
  icu_admission_at text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'atencao',
  diagnoses text NOT NULL DEFAULT '',
  summary text NOT NULL DEFAULT '',
  resp_support text NOT NULL DEFAULT '',
  resp_detail text NOT NULL DEFAULT '',
  hemo_support text NOT NULL DEFAULT '',
  hemo_detail text NOT NULL DEFAULT '',
  neuro_status text NOT NULL DEFAULT '',
  rass text NOT NULL DEFAULT '',
  cam_icu text NOT NULL DEFAULT '',
  renal_detail text NOT NULL DEFAULT '',
  diuresis_24h text NOT NULL DEFAULT '',
  balance_24h text NOT NULL DEFAULT '',
  antibiotics text NOT NULL DEFAULT '',
  cultures text NOT NULL DEFAULT '',
  infection_detail text NOT NULL DEFAULT '',
  diet text NOT NULL DEFAULT '',
  glucose text NOT NULL DEFAULT '',
  labs text NOT NULL DEFAULT '',
  devices text NOT NULL DEFAULT '',
  vte text NOT NULL DEFAULT '',
  stress_ulcer text NOT NULL DEFAULT '',
  skin_mobility text NOT NULL DEFAULT '',
  abcdef text NOT NULL DEFAULT '',
  sofa2 text NOT NULL DEFAULT '',
  goals_of_care text NOT NULL DEFAULT '',
  today_goals text NOT NULL DEFAULT '',
  handoff text NOT NULL DEFAULT '',
  contingency text NOT NULL DEFAULT '',
  archived integer NOT NULL DEFAULT 0,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  medical_history text NOT NULL DEFAULT ''
);

CREATE TABLE tasks (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id text NOT NULL,
  text text NOT NULL,
  priority text NOT NULL DEFAULT 'normal',
  due_at text NOT NULL DEFAULT '',
  completed integer NOT NULL DEFAULT 0,
  completed_at text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE evolutions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id text NOT NULL,
  evolution_date text NOT NULL,
  text text NOT NULL,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  print_json text NOT NULL DEFAULT '',
  source_version integer NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX evolutions_patient_date_unique ON evolutions (patient_id, evolution_date);

CREATE TABLE medical_documents (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id text NOT NULL,
  kind text NOT NULL DEFAULT 'relatorio',
  title text NOT NULL,
  document_date text NOT NULL,
  recipient text NOT NULL DEFAULT '',
  purpose text NOT NULL DEFAULT '',
  content text NOT NULL,
  cid text NOT NULL DEFAULT '',
  cid_authorized integer NOT NULL DEFAULT 0,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  prescriber_name text NOT NULL DEFAULT '',
  prescriber_crm text NOT NULL DEFAULT ''
);
CREATE INDEX medical_documents_patient_date_idx ON medical_documents (patient_id, document_date);

CREATE TABLE prescribers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  crm text NOT NULL,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE UNIQUE INDEX prescribers_name_crm_unique ON prescribers (lower(name), lower(crm));

CREATE TABLE custom_medications (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  text text NOT NULL,
  weight_based integer NOT NULL DEFAULT 0,
  unit text,
  min_dose double precision,
  max_dose double precision,
  concentration double precision,
  concentration_unit text,
  formula text,
  notes text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX custom_medications_name_idx ON custom_medications (name);

CREATE TABLE daily_goals (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id text NOT NULL,
  goal_date text NOT NULL,
  text text NOT NULL,
  completed integer NOT NULL DEFAULT 0,
  completed_at text,
  created_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX daily_goals_patient_date_idx ON daily_goals (patient_id, goal_date);

CREATE TABLE access_attempts (
  id text PRIMARY KEY,
  attempts integer NOT NULL,
  reset_at bigint NOT NULL
);

CREATE TABLE access_sessions (
  id text PRIMARY KEY,
  expires bigint NOT NULL,
  last_seen bigint NOT NULL
);

CREATE TABLE clinical_audit (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id text NOT NULL DEFAULT '',
  action text NOT NULL,
  author text NOT NULL,
  at text NOT NULL,
  before text,
  after text
);
CREATE INDEX clinical_audit_patient_idx ON clinical_audit (patient_id);

CREATE TABLE clinical_records (
  sequence integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id text NOT NULL,
  patient_id text NOT NULL,
  kind text NOT NULL,
  date text NOT NULL,
  version integer NOT NULL,
  status text NOT NULL,
  data text NOT NULL,
  author text NOT NULL,
  source text NOT NULL,
  saved_at text NOT NULL
);
CREATE UNIQUE INDEX clinical_record_revision ON clinical_records (id, version);
CREATE INDEX clinical_patient_kind_date ON clinical_records (patient_id, kind, date);

CREATE TABLE daily_sheets (
  patient_id text PRIMARY KEY,
  admission text NOT NULL DEFAULT '',
  data text NOT NULL,
  version integer NOT NULL DEFAULT 1,
  updated_at text NOT NULL,
  author text NOT NULL
);

CREATE TABLE pep_revisions (
  version integer PRIMARY KEY,
  operation_id text NOT NULL,
  data text NOT NULL,
  source_data text NOT NULL,
  author text NOT NULL,
  saved_at text NOT NULL
);
CREATE UNIQUE INDEX pep_operation_unique ON pep_revisions (operation_id);

-- Auditoria automática de inserções, alterações e exclusões nas tabelas clínicas.
CREATE FUNCTION audit_row() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  row_data jsonb := to_jsonb(CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END);
  pid text := '';
BEGIN
  IF TG_TABLE_NAME = 'patients' THEN pid := row_data->>'id';
  ELSIF row_data ? 'patient_id' THEN pid := row_data->>'patient_id';
  END IF;
  INSERT INTO clinical_audit(patient_id, action, author, at, before, after) VALUES (
    COALESCE(pid, ''),
    TG_TABLE_NAME || '.' || lower(TG_OP),
    'Usuário autenticado',
    to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    CASE WHEN TG_OP <> 'INSERT' THEN to_jsonb(OLD)::text END,
    CASE WHEN TG_OP <> 'DELETE' THEN to_jsonb(NEW)::text END
  );
  RETURN NULL;
END $$;

CREATE TRIGGER audit_patients AFTER INSERT OR UPDATE OR DELETE ON patients FOR EACH ROW EXECUTE FUNCTION audit_row();
CREATE TRIGGER audit_tasks AFTER INSERT OR UPDATE OR DELETE ON tasks FOR EACH ROW EXECUTE FUNCTION audit_row();
CREATE TRIGGER audit_events AFTER INSERT OR UPDATE OR DELETE ON events FOR EACH ROW EXECUTE FUNCTION audit_row();
CREATE TRIGGER audit_evolutions AFTER INSERT OR UPDATE OR DELETE ON evolutions FOR EACH ROW EXECUTE FUNCTION audit_row();
CREATE TRIGGER audit_daily_goals AFTER INSERT OR UPDATE OR DELETE ON daily_goals FOR EACH ROW EXECUTE FUNCTION audit_row();
CREATE TRIGGER audit_medical_documents AFTER INSERT OR UPDATE OR DELETE ON medical_documents FOR EACH ROW EXECUTE FUNCTION audit_row();
CREATE TRIGGER audit_prescribers AFTER INSERT OR UPDATE OR DELETE ON prescribers FOR EACH ROW EXECUTE FUNCTION audit_row();
CREATE TRIGGER audit_custom_medications AFTER INSERT OR UPDATE OR DELETE ON custom_medications FOR EACH ROW EXECUTE FUNCTION audit_row();

CREATE FUNCTION audit_clinical_record() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO clinical_audit(patient_id, action, author, at, before, after) VALUES (
    NEW.patient_id, 'clinical.' || NEW.kind, NEW.author, NEW.saved_at,
    (SELECT data FROM clinical_records WHERE id = NEW.id AND version < NEW.version ORDER BY version DESC LIMIT 1),
    NEW.data
  );
  RETURN NULL;
END $$;
CREATE TRIGGER audit_clinical_insert AFTER INSERT ON clinical_records FOR EACH ROW EXECUTE FUNCTION audit_clinical_record();
