export type Data = Record<string,string>;
export type Kind = 'assessment'|'profile'|'control'|'exam'|'infusion'|'antimicrobial'|'device'|'prescription'|'evolution'|'handoff'|'goal'|'checklist';
export type ClinicalRecord={id:string;patientId:string;kind:Kind;date:string;version:number;status:'draft'|'final';data:Data;source:string;author:string;savedAt:string};
export type Person={id:string;name:string;bed:string;age:string;[key:string]:unknown};
export const kinds:Record<Kind,string>={assessment:'Avaliação diária',profile:'Perfil longitudinal',control:'Controles e balanço',exam:'Exames',infusion:'Infusões',antimicrobial:'Antimicrobianos',device:'Dispositivos',prescription:'Prescrição registrada',evolution:'Evolução estruturada',handoff:'Passagem revisada',goal:'Metas e pendências',checklist:'Checklist da visita'};
export const systems=['Neurológico','Respiratório','Cardiovascular','Renal e metabólico','Infeccioso','Gastrointestinal','Nutricional','Hematológico','Pele e lesão por pressão','Dispositivos','Profilaxias','Mobilidade e reabilitação','Comunicação com familiares','Limitações terapêuticas','Metas do dia','Pendências','Riscos imediatos'];
export const profiles=['Sexo','Procedência','Motivo da internação','Hipóteses diagnósticas','Comorbidades','Alergias','Medicações de uso contínuo','Diretivas antecipadas','Limitações terapêuticas','Isolamento','Terapia renal substitutiva','Alta prevista','Desfecho','Data/hora do desfecho'];
// Recovered from the supplied HTML table, rather than its inconsistent GROUPS array.
const rowLabels=[['TOT','TQT'],['CVC — acesso 1','CVC — acesso 2'],['PAI','SVD'],['Total de entradas'],['Hemocomponentes'],['Campo livre original 6'],['Campo livre original 7'],['Diurese'],['Diálise'],['Fezes','Estase'],['Drenos'],['Campo livre original 12'],['Balanço hídrico'],['PAM mínima','PAM máxima'],['FC mínima','FC máxima'],['FR mínima','FR máxima'],['Temperatura mínima','Temperatura máxima'],['Glicemia mínima','Glicemia máxima'],['PIA/PIC/PVC'],['Antimicrobiano 1'],['Antimicrobiano 2'],['Antimicrobiano 3'],['Antimicrobiano 4'],['DVA 1'],['DVA 2'],['DVA 3'],['Sedação 1'],['Sedação 2'],['Sedação 3'],['Sedação 4'],['GCS/RASS (original)','Pupilas'],['Modo ventilatório'],['Volume minuto','PEEP'],['FR','FiO2'],['pH','BE'],['pO2','SatO2'],['pCO2','Bicarbonato'],['PaO2/FiO2'],['VG','Hb'],['Leucócitos','Bastões'],['Plaquetas'],['RNI','KPTT'],['Cálcio','Fibrinogênio'],['Na','K'],['Creatinina','Ureia'],['Lactato','SvO2'],['ΔCO2','TEC'],['PCR','Mg'],['BT','BD'],['TGO','TGP'],['Amilase','Gama-GT'],['Lipase','Ácido úrico'],['D-dímero','Ferritina'],['BNP','Albumina'],['MB','Troponina']];
const groups:[string,number,number][]=[['Acessos',0,2],['Ganhos',3,6],['Perdas',7,12],['Dados vitais',13,18],['Antimicrobianos',19,22],['Drogas vasoativas',23,25],['Sedação',26,29],['Neurológico',30,30],['Ventilação',31,33],['Gasometria',34,37],['Hematológico',38,42],['Metabólico',43,53],['Cardíaco',54,54]];
export const fichaFields=rowLabels.flatMap((labels,row)=>labels.map((label,slot)=>({key:`f_${row}_${slot}`,label,row,section:groups.find(g=>row>=g[1]&&row<=g[2])![0]})));
export const localDate=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export const localTime=()=>localDate()+'T'+new Date().toTimeString().slice(0,5);
export function number(value:unknown):number|null {if(typeof value!=='string'||!value.trim()||!/^[-+]?\d+(?:[.,]\d+)?$/.test(value.trim()))return null;const n=Number(value.replace(',','.'));return Number.isFinite(n)?n:null;}
export const fmt=(v:number)=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:3}).format(v);
export const scales=[{name:'Glasgow',keys:['gcs_eye','gcs_verbal','gcs_motor'],labels:['Abertura ocular (1–4; NT se não testável)','Resposta verbal (1–5; NT se não testável)','Resposta motora (1–6; NT se não testável)'],bounds:[[1,4],[1,5],[1,6]]},{name:'SOFA clássico — componentes pontuados manualmente',keys:['sofa_resp','sofa_coag','sofa_liver','sofa_cardio','sofa_neuro','sofa_renal'],labels:['Respiratório','Coagulação','Hepático','Cardiovascular','Neurológico','Renal'],bounds:Array(6).fill([0,4])}];
export function score(d:Data,keys:string[],bounds:number[][]){const values=keys.map(k=>number(d[k]));return values.some((n,i)=>n===null||!Number.isInteger(n)||n<bounds[i][0]||n>bounds[i][1])?null:(values as number[]).reduce((a,b)=>a+b,0);}
export const controlLabels:Record<string,string>={pas:'Pressão sistólica (mmHg)',pad:'Pressão diastólica (mmHg)',pam:'PAM medida (mmHg)',fc:'Frequência cardíaca (bpm)',fr:'Frequência respiratória (irpm)',temperature:'Temperatura (°C)',spo2:'SpO₂ (%)',glucose:'Glicemia (mg/dL)',input:'Entradas totais (mL)',urine:'Diurese (mL)',drain:'Drenos / ostomias (mL)',stool:'Perdas digestivas (mL)',dialysis:'Ultrafiltração (mL)',other:'Outras perdas (mL)',weight:'Peso utilizado (kg)',hours:'Período (horas)'};
export function balance(d:Data){const input=number(d.input),out=['urine','drain','stool','dialysis','other'].map(k=>number(d[k]));const u=number(d.urine),w=number(d.weight),h=number(d.hours);return {balance:input!==null&&input>=0&&out.every(n=>n!==null&&n>=0)?input-(out as number[]).reduce((a,b)=>a+b,0):null,urineRate:u!==null&&u>=0&&w!==null&&w>0&&h!==null&&h>0?u/(w*h):null};}
export function infusion(d:Data){const amount=number(d.amount),volume=number(d.volume),weight=number(d.weight),rate=number(d.rate),desired=number(d.desired),max=number(d.maximum);if(!['mcg/kg/min','mcg/kg/h','mg/kg/h','mg/h','mcg/min','UI/h'].includes(d.unit)||(d.unit==='UI/h'?d.amountUnit!=='UI':!['mg','mcg'].includes(d.amountUnit))||amount===null||amount<=0||volume===null||volume<=0)return null;const perKg=d.unit.includes('/kg');if(perKg&&(weight===null||weight<=0))return null;const factor=d.unit.startsWith('mcg')?(d.amountUnit==='mg'?1000:1):d.unit.startsWith('mg')?(d.amountUnit==='mcg'?.001:1):1;const concentration=amount*factor/volume,multiplier=(perKg?weight!:1)*(d.unit.endsWith('/min')?60:1);return {concentration,current:rate!==null&&rate>=0?rate*concentration/multiplier:null,desiredRate:desired!==null&&desired>=0?desired*multiplier/concentration:null,maxRate:max!==null&&max>0?max*multiplier/concentration:null,exceeds:desired!==null&&max!==null&&desired>max,formula:`mL/h = dose × ${perKg?'peso × ':''}${d.unit.endsWith('/min')?'60':'1'} ÷ concentração; concentração = quantidade convertida ÷ volume final`};}
export function validate(kind:Kind,d:Data){const errors:string[]=[];if(kind==='control')for(const [k,label] of Object.entries(controlLabels)){if(!d[k])continue;const n=number(d[k]);if(n===null||n<0||(k==='spo2'&&n>100)||(k==='hours'&&(n<=0||n>24))||(k==='weight'&&n<=0))errors.push(`${label}: valor inválido`);}if(kind==='assessment'){for(const s of scales)s.keys.forEach((k,i)=>{if(!d[k]||(k.startsWith('gcs_')&&d[k]==='NT'))return;const n=number(d[k]);if(n===null||!Number.isInteger(n)||n<s.bounds[i][0]||n>s.bounds[i][1])errors.push(`${s.labels[i]}: intervalo inválido`);});for(const [k,min,max] of [['rass',-5,4],['ramsay',1,6],['braden',6,23],['morse',0,125],['fugulin',9,36]] as const){if(d[k]){const n=number(d[k]);if(n===null||!Number.isInteger(n)||n<min||n>max)errors.push(`${k}: intervalo ${min} a ${max}`);}}}if(kind==='infusion'){for(const k of ['amount','volume','weight','rate','desired','maximum'])if(d[k]&&(number(d[k])===null||number(d[k])!<0))errors.push(`${k}: número inválido`);if(d.amount&&d.volume&&d.unit&&!infusion(d))errors.push('Quantidade, volume, peso ou unidades incompatíveis');if(infusion(d)?.exceeds)errors.push('Dose desejada acima da máxima configurada');}return errors;}
export function latest(rows:ClinicalRecord[],patientId:string,kind:Kind,date?:string){return rows.filter(r=>r.patientId===patientId&&r.kind===kind&&(!date||r.date.slice(0,10)===date)).sort((a,b)=>b.date.localeCompare(a.date)||b.savedAt.localeCompare(a.savedAt))[0];}
export function stableCopy(d:Data){return Object.fromEntries(Object.entries(d).filter(([k])=>['allergies','comorbidities','homeMedication','directives'].includes(k)));}
export function treatmentDay(start:string,ref=localDate()){if(!/^\d{4}-\d{2}-\d{2}/.test(start||''))return null;const a=Date.parse(start.slice(0,10)+'T12:00:00Z'),b=Date.parse(ref.slice(0,10)+'T12:00:00Z');return !Number.isFinite(a)||!Number.isFinite(b)||a>b?null:Math.floor((b-a)/86400000)+1;}
export function aggregateControls(rows:ClinicalRecord[],end:string){const endMs=Date.parse(end),startMs=endMs-86400000;let total=0,hours=0,last=startMs;const intervals=rows.map(r=>({r,start:Date.parse(r.data.start),end:Date.parse(r.date)})).filter(x=>x.end>startMs&&x.end<=endMs).sort((a,b)=>a.start-b.start);for(const x of intervals){const b=balance(x.r.data),h=number(x.r.data.hours);if(!Number.isFinite(x.start)||x.start<startMs||h===null||Math.abs((x.end-x.start)/3600000-h)>.01)return {error:'Períodos ausentes ou divergentes',balance:null,hours};if(x.start<last)return {error:'Intervalos sobrepostos',balance:null,hours};if(b.balance===null)return {error:'Há entradas ou saídas não informadas',balance:null,hours};total+=b.balance;hours+=h;last=x.end;}return {error:intervals.length?'':'Sem controles',balance:intervals.length?total:null,hours};}
export function recordText(r:ClinicalRecord){const d=r.data;if(['prescription','evolution','handoff'].includes(r.kind))return [d.category&&`Categoria: ${d.category}`,d.allergies&&`Alergias conferidas: ${d.allergies}`,d.renal&&`Revisão renal: ${d.renal}`,d.reconciliation&&`Reconciliação: ${d.reconciliation}`,d.text].filter(Boolean).join('\n');if(r.kind==='assessment')return [...['allergies','comorbidities','homeMedication','directives','respSupport','hemoSupport','trs','isolation','timeUnknown','originalPatient','originalAdmission'].map(k=>d[k]&&`${k}: ${d[k]}`),...scales.flatMap(s=>s.keys.map((k,i)=>d[k]&&`${s.labels[i]}: ${d[k]}`)),...systems.map((s,i)=>d[`system_${i}`]&&`# ${s.toUpperCase()}\n${d[`system_${i}`]}`),...fichaFields.map(f=>d[f.key]&&`${f.label}: ${d[f.key]}`),...scales.map(s=>{const total=score(d,s.keys,s.bounds);return total===null?'':`${s.name}: ${s.keys.map(k=>d[k]).join(' + ')} = ${total}`;}),...['rass','ramsay','braden','morse','fugulin'].map(k=>d[k]&&`${k.toUpperCase()} (manual): ${d[k]}`),d.assessment&&`# AVALIAÇÃO\n${d.assessment}`,d.plan&&`# PLANO\n${d.plan}`].filter(Boolean).join('\n');return Object.entries(d).filter(([k,v])=>v&&!['bed','physician'].includes(k)).map(([k,v])=>`${controlLabels[k]||(k.startsWith('profile_')?profiles[Number(k.split('_')[1])]:k)}: ${v}`).join('\n');}
export function evolution(p:Person,rows:ClinicalRecord[],date:string){const a=latest(rows,p.id,'assessment',date),profile=latest(rows,p.id,'profile');return [`# EVOLUÇÃO MÉDICA — UTI ADULTO\nData: ${a?.date||date}\nPaciente: ${p.name}\nLeito: ${p.bed}`,p.admissionAt&&`Internação hospitalar: ${p.admissionAt} · D${treatmentDay(String(p.admissionAt),date)??'não calculável'}`,p.icuAdmissionAt&&`Admissão UTI: ${p.icuAdmissionAt} · D${treatmentDay(String(p.icuAdmissionAt),date)??'não calculável'}`,p.diagnoses&&`# DIAGNÓSTICOS DOCUMENTADOS\n${p.diagnoses}`,profile&&recordText(profile),a&&recordText(a),...rows.filter(r=>r.patientId===p.id&&['control','exam','infusion','antimicrobial','device','goal'].includes(r.kind)&&r.date.slice(0,10)===date).map(r=>`# ${kinds[r.kind].toUpperCase()} — ${r.date} [${r.source}]\n${recordText(r)}`)].filter(Boolean).join('\n\n');}
