'use client';
import {useState} from 'react';
import {clinicalApi} from './Workspace';
const bytes=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const base64=(a:Uint8Array)=>{let s='';for(const b of a)s+=String.fromCharCode(b);return btoa(s);};
async function key(password:string,salt:Uint8Array){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:salt as BufferSource,iterations:310000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
export default function Security(){const [password,setPassword]=useState(''),[message,setMessage]=useState(''),[preview,setPreview]=useState<any>(null),[audit,setAudit]=useState<any[]>([]),[busy,setBusy]=useState(false);
 async function backup(){setBusy(true);try{if(password.length<12)throw Error('Use uma senha de pelo menos 12 caracteres para o backup.');const data=await clinicalApi('?op=backup'),salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(password,salt),new TextEncoder().encode(JSON.stringify(data)));const file={format:'uti-encrypted-v1',salt:base64(salt),iv:base64(iv),data:base64(new Uint8Array(cipher))};const url=URL.createObjectURL(new Blob([JSON.stringify(file)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='uti-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Backup gerado. Guarde a senha separadamente; não há recuperação dessa senha.');}catch(e){setMessage(String(e));}finally{setBusy(false);}}
 return <section className="clinical-workspace"><h2>Segurança, backup e histórico</h2><p>Acesso individual, sessão de até 12 horas e expiração após 15 minutos sem atividade. Dados persistem no banco do sistema. Rascunhos temporários ficam nesta aba e são removidos após salvar.</p><label className="clinical-field">Senha de criptografia do arquivo<input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy} onClick={()=>void backup()}>Baixar backup criptografado</button><label className="clinical-field">Restaurar backup (.json, até 10 MB)<input type="file" accept=".json,application/json" onChange={async e=>{try{setPreview(null);const f=e.target.files?.[0];if(!f)return;if(f.size>10000000)throw Error('Arquivo excede 10 MB');let data=JSON.parse(await f.text());if(data.format==='uti-encrypted-v1'){const clear=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(data.iv)},await key(password,bytes(data.salt)),bytes(data.data));data=JSON.parse(new TextDecoder().decode(clear));}if(data.format!=='uti-backup-v2')throw Error('Formato incompatível');setPreview(data);setMessage('Confira o conteúdo antes de restaurar. Dados existentes não serão sobrescritos.');}catch{setMessage('Não foi possível abrir o backup. Confira formato e senha.');}}}/></label>{preview&&<div><pre>{Object.entries(preview.tables||{}).map(([k,v])=>`${k}: ${Array.isArray(v)?v.length:'inválido'}`).join('\n')}</pre><button disabled={busy} onClick={async()=>{if(!confirm('Restaurar os registros faltantes deste backup? Os existentes serão mantidos.'))return;setBusy(true);try{await clinicalApi('',{action:'restore',backup:preview,confirmed:true});setMessage('Restauração concluída. Recarregue o sistema.');setPreview(null);}catch(e){setMessage(String(e));}finally{setBusy(false);}}}>Confirmar restauração</button></div>}<p role="status">{message}</p><h3>Auditoria</h3><button onClick={async()=>{try{setAudit((await clinicalApi('?op=audit')).rows);}catch(e){setMessage(String(e));}}}>Carregar últimas 300 alterações</button>{audit.map(a=><details key={a.id}><summary>{a.at} · {a.action} · {a.author}</summary><p>Paciente: {a.patient_id||'Sistema'}</p><h4>Antes</h4><pre>{a.before||'—'}</pre><h4>Depois</h4><pre>{a.after||'—'}</pre></details>)}<h3>Retenção</h3><p>Arquivar um paciente preserva o histórico. Não há exclusão automática. Exclusão definitiva e restaurações acima de 800 registros requerem manutenção administrativa com backup prévio.</p></section>;
}
