'use client';
import LegacyImport from './LegacyImport';
import {useEffect,useRef,useState} from 'react';
import {type ClinicalRecord,type Person,type Kind,kinds,systems,profiles,fichaFields,localTime,localDate,scales,score,controlLabels,balance,infusion,fmt,number,validate,recordText,evolution,stableCopy,latest,aggregateControls,treatmentDay} from './model';
import {mergeSheet,type SheetState,type CellProposal} from './intake';
export async function clinicalApi(path='',body?:unknown):Promise<any>{const r=await fetch('/api/clinical'+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const j:any=await r.json();if(!r.ok)throw Error(j.error||'Falha de comunicação');return j;}
function Field({label,value,onChange,type='text',options}:{label:string;value?:string;onChange:(v:string)=>void;type?:string;options?:string[]}){return <label className="clinical-field"><span>{label}</span>{options?<select value={value||''} onChange={e=>onChange(e.target.value)}><option value="">Não informado</option>{options.map(o=><option key={o}>{o}</option>)}</select>:type==='area'?<textarea rows={3} value={value||''} onChange={e=>onChange(e.target.value)}/>:<input type={type} value={value||''} onChange={e=>onChange(e.target.value)}/>}</label>}
export default function Workspace({patients,records,onSaved,requestedPatient,onPatientChange}:{requestedPatient?:string;patients:Person[];records:ClinicalRecord[];onSaved:(r:ClinicalRecord)=>void;onPatientChange?:(id:string)=>void}){
 const [patientId,setPatient]=useState(''),[kind,setKind]=useState<Kind>('assessment'),[current,setCurrent]=useState<ClinicalRecord|null>(null),[state,setState]=useState('Sem alterações'),[error,setError]=useState(''),[history,setHistory]=useState<ClinicalRecord[]>([]),[amendment,setAmendment]=useState(false),[printed,setPrinted]=useState('');
 const ref=useRef(current),dirty=useRef(false),busy=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null),amend=useRef(false);ref.current=current;amend.current=amendment;
 const patient=patients.find(p=>p.id===patientId);const rows=records.filter(r=>r.patientId===patientId&&r.kind===kind).sort((a,b)=>b.date.localeCompare(a.date));
 function stash(r:ClinicalRecord){try{sessionStorage.setItem('uti-native-'+r.id,JSON.stringify(r));}catch{setError('Não foi possível manter a cópia temporária neste navegador. Salve antes de sair.');}}
 async function save(final=false){if(busy.current)return false;const r=ref.current;if(!r||(!dirty.current&&!final))return true;const errors=validate(r.kind,r.data);if(errors.length){setError(errors.join('; '));setState('Erro ao salvar');return false;}busy.current=true;setState(final?'Finalizando':'Salvando');try{const j=await clinicalApi('',{action:'save',record:{...r,status:final?'final':r.status},expectedVersion:r.version,confirmed:final,amendment:amend.current});onSaved(j.record);const changed=ref.current!==r;const updated=changed?{...ref.current!,version:j.record.version}:j.record;ref.current=updated;setCurrent(updated);dirty.current=changed;if(final&&!changed)setAmendment(false);if(changed){stash(updated);timer.current=setTimeout(()=>void save(),700);}else{sessionStorage.removeItem('uti-native-'+r.id);setState('Salvo');setError('');}return true;}catch(e){setError(e instanceof Error?e.message:'Erro ao salvar');setState('Erro ao salvar');return false;}finally{busy.current=false;}}
 function change(key:string,value:string){if(!ref.current)return;const next={...ref.current,data:{...ref.current.data,[key]:value,...((ref.current.kind==='control'||ref.current.kind==='infusion'||key.startsWith('gcs_')||key.startsWith('sofa_'))?{calculatedAt:localTime()}:{})}};ref.current=next;setCurrent(next);dirty.current=true;stash(next);setState('Salvando');if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void save(),700);}
 async function install(r:ClinicalRecord){if(!await save())return;let recovered=r;try{const draft=sessionStorage.getItem('uti-native-'+r.id);if(draft){const x=JSON.parse(draft);if(x.version===r.version&&confirm('Há um rascunho local. Recuperar?')){recovered=x;dirty.current=true;}}}catch{}ref.current=recovered;setCurrent(recovered);setAmendment(false);setHistory([]);setState(dirty.current?'Rascunho recuperado — salve':'Salvo');}
 async function select(p:string,k:Kind){if(!await save())return;setPatient(p);setKind(k);setCurrent(null);ref.current=null;setHistory([]);setAmendment(false);try{const pending=Object.keys(sessionStorage).filter(x=>x.startsWith('uti-native-')).map(x=>JSON.parse(sessionStorage.getItem(x)!)).find(x=>x.patientId===p&&x.kind===k);if(pending&&confirm('Recuperar rascunho não concluído?')){setCurrent(pending);ref.current=pending;dirty.current=true;setState('Rascunho recuperado — salve');}}catch{}}
 async function create(data:Record<string,string>={}){if(!patient||!await save())return;const r:ClinicalRecord={id:crypto.randomUUID(),patientId,kind,date:localTime(),status:'draft',version:0,data:{bed:patient.bed,...data},source:'Manual — pendente de conferência',author:'',savedAt:''};dirty.current=true;ref.current=r;setCurrent(r);setAmendment(false);setHistory([]);stash(r);setState('Rascunho — preencha e salve');}
 useEffect(()=>{const unload=(e:BeforeUnloadEvent)=>{if(dirty.current||busy.current)e.preventDefault();};const online=()=>{if(dirty.current)void save();};window.addEventListener('beforeunload',unload);window.addEventListener('online',online);return()=>{window.removeEventListener('beforeunload',unload);window.removeEventListener('online',online);};},[]);
 useEffect(()=>{if(requestedPatient&&requestedPatient!==patientId)void select(requestedPatient,kind);},[requestedPatient]);
 useEffect(()=>{if(!patientId&&patients.length)void select(patients[0].id,kind);},[patients,patientId]);
 const field=(key:string,label:string,type='text',options?:string[])=><Field key={key} label={label} value={current?.data[key]} onChange={v=>change(key,v)} type={type} options={options}/>;
 const d=current?.data||{},locked=current?.status==='final'&&!amendment;const b=balance(d),inf=infusion(d);const errors=current?validate(kind,d):[];
 async function copy(){try{await navigator.clipboard.writeText(current?recordText(current):'');setState('Texto copiado');}catch{setError('Cópia indisponível. Selecione o texto da prévia.');}}
 async function sendToSheet(){
  if(!current||kind!=='assessment'||!patientId)return;
  if(!await save())return;
  const values=Object.fromEntries(Object.entries(ref.current?.data||{}).filter(([key,value])=>key.startsWith('f_')&&value?.trim())) as CellProposal;
  if(!Object.keys(values).length){setState('Nenhum campo da ficha preenchido nesta avaliação');return;}
  try{
   const response=await fetch('/api/ficha?patientId='+encodeURIComponent(patientId),{cache:'no-store'});
   const body=await response.json() as {sheet?:SheetState;version?:number;error?:string};
   if(!response.ok||!body.sheet)throw Error(body.error||'Falha ao carregar a ficha');
   const merged=mergeSheet(body.sheet,current.date.slice(0,10),values);
   if(merged.added){
    const saved=await fetch('/api/ficha?patientId='+encodeURIComponent(patientId),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sheet:merged.sheet,version:body.version||0})});
    const result=await saved.json() as {error?:string};
    if(!saved.ok)throw Error(result.error||'Falha ao salvar a ficha');
   }
   setState(`Ficha atualizada: ${merged.added} célula(s); ${merged.conflicts.length} divergência(s) preservada(s)`);
  }catch(e){setError(e instanceof Error?e.message:'Falha ao sincronizar ficha');}
 }
 return <section className="clinical-workspace"><header className="clinical-toolbar"><select aria-label="Selecionar paciente" value={patientId} onChange={e=>{onPatientChange?.(e.target.value);void select(e.target.value,kind);}}><option value="">Selecione um paciente</option>{patients.map(p=><option key={p.id} value={p.id}>{p.bed} · {p.name}</option>)}</select><button disabled={!patient} onClick={()=>void create()}>+ Novo registro</button><span role="status">{state}</span></header>
 <nav className="clinical-tabs" aria-label="Módulos clínicos">{Object.entries(kinds).map(([k,label])=><button className={kind===k?'active':''} key={k} onClick={()=>void select(patientId,k as Kind)}>{label}</button>)}</nav>
 {error&&<p role="alert" className="clinical-error">{error} <button onClick={()=>void save()}>Tentar salvar</button></p>}
 {kind==='assessment'&&<LegacyImport patientId={patientId} onSaved={onSaved}/>}<div className="clinical-layout"><aside><h3>{kinds[kind]}</h3>{rows.length===0&&<p>Nenhum registro.</p>}{rows.map(r=><button className="clinical-history" key={r.id} onClick={()=>void install(r)}>{r.date.replace('T',' ')}<small>{r.status==='final'?'Finalizado':'Em andamento'} · v{r.version}</small></button>)}</aside>
 <div>{!current?<div className="clinical-empty">Selecione um registro ou crie uma avaliação. Os campos começam vazios.</div>:<>
 <div className="clinical-actions"><button onClick={()=>void save()} disabled={!!locked}>Salvar</button>{kind==='assessment'&&<button onClick={()=>void sendToSheet()}>Enviar campos à ficha A4</button>}<button disabled={!!locked} onClick={async()=>{if(confirm('Revise todos os dados. Finalizar este documento?'))await save(true);}}>Finalizar</button>{locked&&<button onClick={()=>{if(confirm('Abrir retificação mantendo a versão anterior?')){setAmendment(true);const next={...current,status:'draft' as const};ref.current=next;setCurrent(next);dirty.current=true;stash(next);}}}>Retificar</button>}<button onClick={async()=>{try{setHistory((await clinicalApi('?history='+current.id)).records);}catch(e){setError(String(e));}}}>Histórico</button><button onClick={()=>{if(confirm('Duplicar todo o conteúdo como rascunho para revisão? Dados diários precisam ser reavaliados.'))void create({...current.data});}}>Duplicar para revisão</button><button onClick={()=>void copy()}>Copiar</button><button onClick={()=>{setPrinted(`${patient?.name} · Leito ${d.bed}\n${current.date} · ${d.physician||'Médico não informado'}\n${recordText(current)}`);document.body.dataset.print='clinical';setTimeout(()=>window.print(),100);}}>Imprimir A4</button></div>
 {history.map(r=><div className="clinical-revision" key={r.version}><details><summary>Versão {r.version} · {r.savedAt} · {r.status}</summary><pre>{recordText(r)}</pre><button onClick={()=>{if(confirm('Recuperar conteúdo como nova versão em rascunho?')){const next={...current,data:r.data,status:'draft' as const};ref.current=next;setCurrent(next);setAmendment(true);dirty.current=true;stash(next);}}}>Recuperar esta versão</button></details></div>)}
 <fieldset disabled={!!locked||state==='Finalizando'}><div className="clinical-grid"><Field label={d.timeUnknown?"Data original (horário não informado)":"Data e horário do registro"} type={d.timeUnknown?"date":"datetime-local"} value={current.date} onChange={v=>{const next={...current,date:v};ref.current=next;setCurrent(next);dirty.current=true;stash(next);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void save(),700);}}/>{field('physician','Médico / CRM')}{field('bed','Leito no registro')}<Field label="Origem / conferência" value={current.source} onChange={v=>{const next={...current,source:v};ref.current=next;setCurrent(next);dirty.current=true;stash(next);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void save(),700);}} options={['Manual — pendente de conferência','Manual — confirmado','Transcrito — pendente de conferência','Transcrito — confirmado']}/></div>
 {kind==='assessment'&&<><div className="clinical-grid">{field('respSupport','Suporte respiratório','text',['Ar ambiente','Oxigenoterapia','VNI','VM invasiva'])}{field('hemoSupport','Suporte vasoativo','text',['Sem DVA','Com DVA'])}{field('trs','TRS atual','text',['Não','Sim'])}{field('isolation','Isolamento atual')}</div><p>Preenchimento: {systems.filter((_,i)=>d['system_'+i]?.trim()).length}/{systems.length} sistemas. Ausência de dados não significa normalidade.</p><details><summary>Dados estáveis</summary><div className="clinical-grid">{field('allergies','Alergias')}{field('comorbidities','Comorbidades')}{field('homeMedication','Medicações habituais')}{field('directives','Diretivas antecipadas')}</div><button onClick={()=>{const prev=records.filter(r=>r.patientId===patientId&&r.kind==='assessment'&&r.date.slice(0,10)<current.date.slice(0,10)).sort((a,b)=>b.date.localeCompare(a.date))[0];if(!prev)return setError('Sem avaliação anterior.');if(confirm('Copiar apenas alergias, comorbidades, medicamentos habituais e diretivas? Revise antes de salvar.'))Object.entries(stableCopy(prev.data)).forEach(([k,v])=>change(k,v));}}>Replicar dados estáveis anteriores</button></details><div className="clinical-grid">{systems.map((s,i)=>field('system_'+i,s,'area'))}{field('assessment','Avaliação clínica','area')}{field('plan','Plano','area')}</div>
 <h3>Escalas — conferência manual</h3>{scales.map(s=><div key={s.name}><h4>{s.name}</h4><div className="clinical-grid">{s.keys.map((k,i)=>field(k,s.labels[i]))}</div><output>{score(d,s.keys,s.bounds)===null?'Dados incompletos ou inválidos — sem resultado':`${s.keys.map(k=>d[k]).join(' + ')} = ${score(d,s.keys,s.bounds)}`}</output><small> Calculado / conferido em: {d.calculatedAt||"preencha os componentes"}. SOFA: registrar componentes já pontuados; não é SOFA-2.</small></div>)}<div className="clinical-grid">{['RASS (-5 a +4)','Ramsay (1 a 6)','Braden (6 a 23)','Morse (0 a 125)','Fugulin (9 a 36)'].map(x=>field(x.split(' ')[0].toLowerCase(),x+' — total manual'))}</div>
 {d.sourceText&&<details><summary>Texto original recebido</summary><pre>{d.sourceText}</pre></details>}<h3>Ficha original — todos os campos</h3>{Array.from(new Set(fichaFields.map(f=>f.section))).map(section=><details key={section}><summary>{section}</summary><div className="clinical-grid">{fichaFields.filter(f=>f.section===section).map(f=>field(f.key,f.label))}</div></details>)}</>}
 {kind==='profile'&&<><div className="clinical-grid">{profiles.map((s,i)=>field('profile_'+i,s,'area'))}</div><h3>Linha do tempo — registros clínicos</h3>{records.filter(r=>r.patientId===patientId).sort((a,b)=>b.date.localeCompare(a.date)).map(r=><details key={r.id}><summary>{r.date} · {kinds[r.kind]} · {r.status==='final'?'Finalizado':'Em andamento'} · v{r.version}</summary><pre>{recordText(r)}</pre></details>)}</>}
 {kind==='control'&&<><div className="clinical-grid">{field('start','Início do intervalo','datetime-local')}{Object.entries(controlLabels).map(([k,l])=>field(k,l))}</div><p>Informe zero apenas quando a ausência de perdas estiver confirmada.</p><output>Balanço = entradas − (diurese + drenos + perdas digestivas + ultrafiltração + outras): {b.balance===null?'dados incompletos':fmt(b.balance)+' mL'}<br/>Diurese = volume ÷ peso ÷ período: {b.urineRate===null?'dados incompletos':fmt(b.urineRate)+' mL/kg/h'}</output><p>{(()=>{const a=aggregateControls(records.filter(r=>r.patientId===patientId&&r.kind==='control'),current.date);return a.error||`Acumulado: ${fmt(a.balance!)} mL em ${fmt(a.hours)} h ${a.hours===24?'(24 horas)':'(parcial)'}`;})()}</p><Trend rows={rows}/><table><caption>Controles registrados — valores seriados</caption><thead><tr><th>Data</th><th>PAM</th><th>FC</th><th>SpO₂</th><th>Balanço mL</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.date}</td><td>{r.data.pam||'—'}</td><td>{r.data.fc||'—'}</td><td>{r.data.spo2||'—'}</td><td>{balance(r.data).balance??'—'}</td></tr>)}</tbody></table></>}
 {kind==='exam'&&<><div className="clinical-grid">{field('name','Exame')}{field('value','Valor')}{field('unit','Unidade')}{field('reference','Referência do laboratório')}{field('origin','Laboratório / origem')}{field('confirmation','Conferência','text',['Pendente','Transcrito','Confirmado'])}</div>{field('text','Laudo / texto colado','area')}<label>Importar texto simples (.txt, até 1 MB)<input type="file" accept=".txt,text/plain" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(!f.name.endsWith('.txt')||f.size>1000000)return setError('Selecione .txt de até 1 MB');change('text',await f.text());change('origin','Arquivo: '+f.name);change('confirmation','Pendente');}}/></label><table><caption>Resultados anteriores (não interpretados como diagnósticos)</caption><tbody>{rows.map(r=><tr key={r.id}><td>{r.date}</td><td>{r.data.name}</td><td>{r.data.value} {r.data.unit}</td><td>{r.data.confirmation}</td></tr>)}</tbody></table></>}
 {kind==='infusion'&&<><div className="clinical-grid">{field('drug','Fármaco')}{field('amount','Quantidade total')}{field('amountUnit','Unidade da quantidade','text',['mg','mcg','UI'])}{field('diluent','Diluente')}{field('volume','Volume final (mL)')}{field('rate','Velocidade atual (mL/h)')}{field('weight','Peso utilizado (kg)')}{field('unit','Unidade da dose','text',['mcg/kg/min','mcg/kg/h','mg/kg/h','mg/h','mcg/min','UI/h'])}{field('desired','Dose desejada')}{field('maximum','Dose máxima configurada')}{field('start','Início','datetime-local')}</div><output>{inf?<>{inf.formula}<br/>Concentração: {fmt(inf.concentration)} {d.unit.split('/')[0]}/mL<br/>Dose atual: {inf.current===null?'—':fmt(inf.current)} {d.unit}<br/>Velocidade para dose desejada: {inf.desiredRate===null?'—':fmt(inf.desiredRate)+' mL/h'}</>:'Preencha quantidade, volume e unidades compatíveis (peso se necessário).'}</output><p>Cálculo para conferência. A gravação não administra nem prescreve medicamentos.</p></>}
 {kind==='antimicrobial'&&<div className="clinical-grid">{field('drug','Antimicrobiano')}{field('start','Início','date')}{field('end','Fim previsto / realizado','date')}{field('indication','Indicação documentada')}{field('dose','Dose / via / intervalo')}{field('culture','Culturas')}<output>Dia de tratamento: {treatmentDay(d.start,current.date)??'não calculável'}</output></div>}
 {kind==='device'&&<div className="clinical-grid">{field('device','Dispositivo')}{field('site','Sítio')}{field('start','Inserção','datetime-local')}{field('end','Retirada','datetime-local')}{field('review','Necessidade / intercorrências','area')}</div>}
 {['prescription','evolution','handoff'].includes(kind)&&<>{kind==='prescription'&&<div className="clinical-grid">{field('category','Categoria','text',['Horário','Se necessário','Profilaxia','Antimicrobiano','Sedoanalgesia','Vasoativo','Soluções e eletrólitos','Nutrição','Cuidados'])}{field('allergies','Alergias conferidas')}{field('renal','Revisão renal')}{field('reconciliation','Reconciliação medicamentosa','area')}</div>}{kind!=='prescription'&&<button onClick={()=>{if(patient&&confirm('Gerar rascunho apenas dos dados documentados desta data?'))change('text',evolution(patient,records,current.date.slice(0,10)));}}>Gerar dos dados registrados</button>}{field('text','Texto para revisão antes de finalizar','area')}</>}
 {kind==='goal'&&<><div className="clinical-grid">{field('system','Sistema')}{field('text','Meta / pendência','area')}{field('priority','Prioridade','text',['Rotina','Alta','Imediata'])}{field('due','Prazo','datetime-local')}{field('responsible','Responsável')}{field('status','Status','text',['Aberta','Em andamento','Concluída'])}{field('notes','Observações','area')}</div>{d.due&&d.status!=='Concluída'&&Date.parse(d.due)<Date.now()&&<p>Prazo vencido</p>}<button onClick={()=>{if(confirm('Criar uma nova meta para amanhã? Revise o prazo.')){const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);void create({...d,due:localDate(tomorrow)+'T08:00',status:'Aberta'});}}}>Replicar para amanhã</button></>}
 {kind==='checklist'&&<div className="clinical-grid">{['Identificação e alergias','Dispositivos','Profilaxias','Sedoanalgesia','Mobilidade','Nutrição','Antimicrobianos','Metas','Família','Passagem revisada'].map((s,i)=>field('check_'+i,s,'text',['Pendente','Conferido','Não se aplica']))}</div>}
 </fieldset>{errors.length>0&&<p className="clinical-error">{errors.join('; ')}</p>}<details><summary>Resumo estruturado</summary><pre>{recordText(current)||'Nenhum conteúdo preenchido.'}</pre></details></> }</div></div><article className="native-print"><pre>{printed}</pre></article></section>;
}

function Trend({rows}:{rows:ClinicalRecord[]}){const values=rows.filter(r=>number(r.data.pam)!==null).sort((a,b)=>a.date.localeCompare(b.date)).slice(-12);if(values.length<2)return <p>Tendência de PAM: registre pelo menos dois valores. Valores numéricos permanecem na tabela.</p>;const nums=values.map(r=>number(r.data.pam)!),min=Math.min(...nums)-5,max=Math.max(...nums)+5;return <figure><figcaption>PAM (mmHg) — últimos {values.length} registros, em ordem temporal</figcaption><svg role="img" aria-label="Tendência de pressão arterial média; valores completos na tabela" viewBox="0 0 600 150"><polyline fill="none" stroke="#235b8d" strokeWidth="3" points={nums.map((n,i)=>`${20+i*560/(nums.length-1)},${120-(n-min)/(max-min)*100}`).join(' ')}/>{nums.map((n,i)=><g key={i}><circle cx={20+i*560/(nums.length-1)} cy={120-(n-min)/(max-min)*100} r="4" fill="#235b8d"/><text x={20+i*560/(nums.length-1)} y={110-(n-min)/(max-min)*100} textAnchor="middle" fontSize="12">{n}</text></g>)}</svg></figure>;}
