import test from 'node:test';import assert from 'node:assert/strict';
import {createEmptyBed,icuReducer,A} from '../app/pep/core/icuStore.js';
import {SUMMARY_SECTIONS,DAY_SECTIONS,CHART_HANDOFF,chartToken,identityOf,applyChart,validateChart,chartPrompt,organizeFromRecords} from '../app/pep/core/chartOrganization.js';
const empty=keys=>Object.fromEntries(keys.map(k=>[k,'']));
function bed(){return {...createEmptyBed('01'),status:'occupied',patientId:'p1',episodeId:'episode1',patientName:'SINTÉTICO',hospitalAdmissionDate:'2026-09-20',admissionDate:'2026-09-20',dates:['2026-09-27','','','','',''],cells:{'0:7:0':'1000'},dailyRecords:{'2026-09-20':{date:'2026-09-20',cells:{'7:0':'900'},evolution:{texto:'# História e intercorrências:\nHISTÓRIA ANTIGA',clinicalDate:'2026-09-20'},evolutionRevisions:[{texto:'HISTÓRIA ANTIGA'}]}},evolucao:{texto:'ATUAL MAIS RECENTE',clinicalDate:'2026-09-28'},handoff:{...createEmptyBed('01').handoff,checklist:[{id:'task1',texto:'TAREFA ORIGINAL',status:'realizado'}]}};}
const day=(data='2026-09-20')=>({data,secoes:{...empty(Object.keys(DAY_SECTIONS)),historia_intercorrencias:'INTERCORRÊNCIA DOCUMENTADA',diagnosticos:'HIPÓTESE DOCUMENTADA',condutas:'PLANO DOCUMENTADO'},ficha:[],passagem:Object.fromEntries(CHART_HANDOFF.map(k=>[k,[]]))});
async function doc(b=bed()){return {...identityOf(b,await chartToken(b)),resumo_internacao:{...empty(Object.keys(SUMMARY_SECTIONS)),curso_clinico:'20/09/2026: CURSO DOCUMENTADO'},dias:[day()]};}
test('importação organiza data, complementa seções, alimenta passagem e mantém a evolução atual',async()=>{const b=bed(),d=await doc(b),result=applyChart(b,d);assert.match(result.hospitalizationSummary.texto,/CURSO DOCUMENTADO/);assert.match(result.dailyRecords['2026-09-20'].evolution.texto,/HISTÓRIA ANTIGA/);assert.match(result.dailyRecords['2026-09-20'].evolution.texto,/INTERCORRÊNCIA DOCUMENTADA/);assert.equal(result.dailyRecords['2026-09-20'].evolutionRevisions.length,2);assert.equal(result.evolucao.texto,'ATUAL MAIS RECENTE');assert.deepEqual(result.handoffByDate['2026-09-20'].condutas,['PLANO DOCUMENTADO']);assert.deepEqual(result.handoffByDate['2026-09-20'].diagnosticos,['HIPÓTESE DOCUMENTADA']);assert.deepEqual(result.handoff.checklist,b.handoff.checklist);assert.equal(result.dailyRecords['2026-09-20'].evolution.payload.condutas[0],'PLANO DOCUMENTADO');assert.equal(result.chartImports.length,1);});
test('campos vazios não apagam dados e conflito de ficha conserva o existente até revisão explícita',async()=>{const b=bed(),d=await doc(b);d.dias=[{...day('2026-09-27'),ficha:[{row:7,slot:0,value:'2000'}]}];let result=applyChart(b,d);assert.equal(result.cells['0:7:0'],'1000');assert.equal(result.dailyRecords['2026-09-27'].cells['7:0'],'1000');result=applyChart(b,d,{cells:{'2026-09-27:7:0':'replace'}});assert.equal(result.cells['0:7:0'],'2000');d.dias[0].ficha[0].value='';result=applyChart(b,d,{cells:{'2026-09-27:7:0':'replace'}});assert.equal(result.cells['0:7:0'],'1000');});
test('dez dias além da folha atual ficam no histórico e mantêm seis colunas',async()=>{const b=bed(),d=await doc(b);d.dias=Array.from({length:10},(_,i)=>day('2026-09-'+(20+i)));const result=applyChart(b,d);assert.equal(Object.keys(result.dailyRecords).length,10);assert.equal(result.dates.length,6);assert.equal(result.evolucao.clinicalDate,'2026-09-29');assert.equal(result.dailyRecords['2026-09-20'].cells['7:0'],'900');});
test('rejeita paciente, episódio, nome, leito, admissão, datas impossíveis, duplicidades e estrutura',async()=>{const b=bed(),d=await doc(b);for(const k of ['patient_id','episode_id','nome','leito','data_admissao'])assert.throws(()=>validateChart({...d,[k]:'outro'},b),/divergente/);for(const date of ['2026-02-30','2026-09-19','30/09/2026'])assert.throws(()=>validateChart({...d,dias:[day(date)]},b));assert.throws(()=>validateChart({...d,dias:[day(),day()]},b),/duplicada/);for(const ficha of [[{row:5,slot:0,value:'x'}],[{row:7,slot:1,value:'x'}],[{row:7,slot:0,value:'x'},{row:7,slot:0,value:'y'}]])assert.throws(()=>validateChart({...d,dias:[{...day(),ficha}]},b),/Célula/);assert.throws(()=>validateChart({...d,extra:'x'},b),/Estrutura/);assert.throws(()=>validateChart({...d,dias:[{...day(),secoes:'texto'}]},b),/Estrutura/);assert.deepEqual(validateChart('```json\n'+JSON.stringify(d)+'\n```',b),d);});
test('revisão pode manter/substituir evolução e preserva versões e campos antigos sem equivalente',async()=>{const b=bed(),d=await doc(b);b.legacyCustom='CAMPO HISTÓRICO';const kept=applyChart(b,d,{days:{'2026-09-20':'keep'}});assert.equal(kept.dailyRecords['2026-09-20'].evolution.texto,b.dailyRecords['2026-09-20'].evolution.texto);const replaced=applyChart(b,d,{days:{'2026-09-20':'replace'}});assert.doesNotMatch(replaced.dailyRecords['2026-09-20'].evolution.texto,/HISTÓRIA ANTIGA/);assert.equal(replaced.dailyRecords['2026-09-20'].evolutionRevisions[0].texto,'HISTÓRIA ANTIGA');assert.equal(replaced.legacyCustom,'CAMPO HISTÓRICO');assert.throws(()=>applyChart(b,d,{days:{'2026-09-20':'delete'}}),/Opções/);});
test('prompt contém somente o paciente escolhido, fontes de todos os dias e vínculo de revisão',async()=>{const b=bed(),token=await chartToken(b),prompt=chartPrompt(b,token,'NOTA ADICIONAL DOCUMENTADA');assert.ok(prompt.includes(token));assert.ok(prompt.includes('2026-09-20'));assert.ok(prompt.includes('NOTA ADICIONAL DOCUMENTADA'));assert.ok(prompt.includes('episode1'));assert.notEqual(token,await chartToken({...b,bedId:'02'}));const result=organizeFromRecords(b,token);assert.match(result.resumo_internacao.curso_clinico,/HISTÓRIA ANTIGA/);assert.match(result.resumo_internacao.curso_clinico,/2026-09-27/);assert.deepEqual(result.dias,[]);});
test('reducer sincroniza importação em folha visível e passa a recuperar dados por data',async()=>{const b=bed(),d=await doc(b);d.dias=[{...day('2026-09-27'),ficha:[{row:44,slot:0,value:'1,7 mg/dL'}]}];const result=icuReducer({beds:{'01':b}},{type:A.IMPORT_CHART,bedId:'01',document:d});assert.equal(result.beds['01'].dailyRecords['2026-09-27'].cells['44:0'],'1,7 mg/dL');assert.equal(result.beds['01'].cells['0:44:0'],'1,7 mg/dL');assert.equal(result.beds['01'].handoffDate,'2026-09-27');assert.equal(result.beds['01'].handoff.checklist[0].status,'realizado');});
test('resumo sem dias conserva os campos atuais de passagem ainda sem metadado de data',async()=>{const b=bed();b.handoff.diagnosticos=['DIAGNÓSTICO LEGADO'];b.handoff.antecedentes_historia=['ANTECEDENTE LEGADO'];b.handoff.overrides={diagnosticos:true};const d=await doc(b);d.dias=[];const r=icuReducer({beds:{'01':b}},{type:A.IMPORT_CHART,bedId:'01',document:d});assert.deepEqual(r.beds['01'].handoff,b.handoff);assert.equal(r.beds['01'].handoffDate,'2026-09-27');});
test('resumo dos registros inclui notas e passagem de datas fora da folha mesmo sem ficha',async()=>{const b=bed();b.notesByDate={'2026-09-21':'NOTA DO DIA 21'};b.handoffByDate={'2026-09-22':{condutas:['PLANO DO DIA 22']}};const token=await chartToken(b),result=organizeFromRecords(b,token);assert.match(result.resumo_internacao.curso_clinico,/2026-09-21\nNOTA DO DIA 21/);assert.match(result.resumo_internacao.curso_clinico,/2026-09-22\ncondutas: PLANO DO DIA 22/);});
