import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {build} from 'esbuild';
fs.mkdirSync('.sites-runtime/tests',{recursive:true});
await build({entryPoints:['worker/evolution-api.ts'],bundle:true,platform:'node',format:'esm',outfile:'.sites-runtime/tests/evolution-api.mjs'});
const {generateEvolution,assembleEvolution}=await import('../.sites-runtime/tests/evolution-api.mjs');
function database(){const sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));const db={prepare(text){let args=[];return {bind(...a){args=a;return this},async first(){return sql.prepare(text).get(...args)||null},async all(){return {results:sql.prepare(text).all(...args)}},async run(){const r=sql.prepare(text).run(...args);return {meta:{changes:Number(r.changes)}}}}}};sql.prepare('INSERT INTO patients(id,bed,name) VALUES (?,?,?)').run('p1','01','PACIENTE SINTÉTICO');const sheet={patient:'PACIENTE SINTÉTICO',admission:'',bed:'01',dates:['27/09/2026','28/09/2026','','','',''],cells:{'0:38:1':'9 g/dL','1:38:1':'10 g/dL','1:13:0':'65'}};sql.prepare('INSERT INTO daily_sheets(patient_id,admission,data,version,updated_at,author) VALUES (?,?,?,?,?,?)').run('p1','',JSON.stringify(sheet),2,'2026-09-28T12:00:00Z','Teste');return {db,sql}};
const request=(version=2,day=1)=>new Request('https://unit.test/api/evolution/generate',{method:'POST',body:JSON.stringify({patientId:'p1',day,version})});
test('versão da ficha impede geração a partir de uma edição não salva',async()=>{const {db}=database();const r=await generateEvolution(request(1),db,'chave-sintetica');assert.equal(r.status,409)});
test('sem dados do dia ou sem chave não gera evolução',async()=>{const {db}=database();assert.equal((await generateEvolution(request(),db,'')).status,503);assert.equal((await generateEvolution(request(2,2),db,'chave-sintetica')).status,400)});
test('resposta estruturada preserva evidência temporal e omite seções vazias',async()=>{const {db,sql}=database();const original=globalThis.fetch;let payload;globalThis.fetch=async(_url,init)=>{payload=JSON.parse(init.body);const fields=Object.fromEntries(payload.text.format.schema.required.map(k=>[k,'']));fields.vitals='PAM mínima de 65 mmHg.';fields.exams='Hb 10 g/dL em 28/09/2026, ante 9 g/dL em 27/09/2026.';return Response.json({output:[{content:[{type:'output_text',text:JSON.stringify(fields)}]}]})};try{const r=await generateEvolution(request(),db,'chave-sintetica');assert.equal(r.status,200);const result=await r.json();assert.match(result.text,/SINAIS VITAIS/);assert.doesNotMatch(result.text,/INTERCORRÊNCIAS/);assert.equal(result.print.exams,'Hb 10 g/dL em 28/09/2026, ante 9 g/dL em 27/09/2026.');assert.equal(payload.store,false);assert.equal(payload.model,'gpt-5-mini');const input=JSON.parse(payload.input);assert.ok(input.current.data.some(x=>x.includes('10 g/dL')));assert.ok(input.previousDays[0].data.some(x=>x.includes('9 g/dL')));assert.equal(sql.prepare("SELECT COUNT(*) n FROM clinical_audit WHERE action='evolution.generate'").get().n,1)}finally{globalThis.fetch=original}});
test('montagem do texto e impressão derivam dos mesmos campos',()=>{const fields={diagnoses:'Hipótese A',summary:'',therapies:'',devices:'',vitals:'',events:'',physical:'',exams:'',assessment:'',plan:'',fastHug:'',pending:'',antecedents:'',prophylaxis:'',antibiotics:'',supports:''};const result=assembleEvolution(fields,{name:'SINTÉTICO',bed:'01',date:'28/09/2026'});assert.equal(result.print.diagnoses,'Hipótese A');assert.equal(result.print.antibiotics,'');assert.equal((result.text.match(/^#/gm)||[]).length,1)});
test('texto único é organizado sem substituir o registro original e usa a chave no servidor',async()=>{
 const {db,sql}=database();const original=globalThis.fetch;let payload;
 globalThis.fetch=async(_url,init)=>{payload=JSON.parse(init.body);const fields=Object.fromEntries(payload.text.format.schema.required.map(k=>[k,'']));fields.vitals='PAM mínima 65 mmHg';fields.pending='Conferir culturas';return Response.json({output:[{content:[{type:'output_text',text:JSON.stringify(fields)}]}]})};
 try{const source='PAM mínima 65 mmHg. Conferir culturas.';const req=new Request('https://unit.test/api/evolution/generate',{method:'POST',body:JSON.stringify({patientId:'p1',day:1,version:2,sourceText:source})});const response=await generateEvolution(req,db,'chave-sintetica');assert.equal(response.status,200);const data=await response.json();assert.equal(data.sourceText,source);assert.match(data.text,/PAM mínima 65 mmHg/);assert.equal(data.print.pending,'Conferir culturas');assert.equal(payload.store,false);assert.equal(JSON.parse(payload.input).sourceEvolution,source);assert.equal(sql.prepare("SELECT COUNT(*) n FROM clinical_audit WHERE action='evolution.generate'").get().n,1)}finally{globalThis.fetch=original}
});
