import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {database as pgDatabase} from './helpers/pg.mjs';import {mockClaude,KEY} from './helpers/claude-mock.mjs';import{build}from'esbuild';
await build({entryPoints:['worker/pep-api.ts'],bundle:true,platform:'node',format:'esm',outfile:'.sites-runtime/tests/pep-api.mjs'});
await build({entryPoints:['worker/pep-ai.ts'],bundle:true,platform:'node',format:'esm',outfile:'.sites-runtime/tests/pep-ai.mjs'});
const {handlePepApi,loadPep}=await import('../.sites-runtime/tests/pep-api.mjs');const {handlePepAI}=await import('../.sites-runtime/tests/pep-ai.mjs');
async function database(){const {db,sql}=await pgDatabase();await sql.prepare('INSERT INTO patients(id,bed,name,admission_at,icu_admission_at,medical_history)VALUES(?,?,?,?,?,?)').run('p1','01','PACIENTE SINTÉTICO','2026-09-20','2026-09-20','ANTECEDENTE EXPLÍCITO');return {db,sql};}
const post=async(db,actions,meta)=>{const m=meta||await loadPep(db);return handlePepApi(new Request('https://test/api/pep',{method:'POST',body:JSON.stringify({actions,version:m.version,sourceToken:m.sourceToken})}),db)};
const action=(type,extra={})=>({type,bedId:'01',patientId:'p1',episodeId:'p1',...extra});
test('migração virtual preserva IDs, campos antigos, datas e nenhum dado é escrito em GET',async()=>{const{db,sql}=await database();const loaded=await loadPep(db);assert.equal(loaded.state.beds['01'].patientId,'p1');assert.equal(loaded.state.beds['01'].handoff.antecedentes_historia[0],'ANTECEDENTE EXPLÍCITO');assert.equal((await sql.prepare('SELECT count(*) n FROM pep_revisions').get()).n,0);});
test('ficha e rascunhos centrais, oito dias, revisão e conflito de sessão',async()=>{const{db,sql}=await database();let r=await post(db,[action('SET_DATE',{day:0,value:'2026-09-20',cascade:false}),action('SET_CELL',{day:0,row:7,slot:0,value:'1.000 mL'}),action('UPDATE_BED',{patch:{evolutionDrafts:{'2026-09-20':'RASCUNHO DOCUMENTADO'}}})]);assert.equal(r.status,200,JSON.stringify(await r.clone().json()));let m=await r.json();assert.equal(m.state.beds['01'].cells['0:7:0'],'1.000 mL');assert.equal((await post(db,[action('SET_CELL',{day:0,row:7,slot:0,value:'2.000'})],{version:0,sourceToken:m.sourceToken})).status,409);
 const daily={...m.state.beds['01'].dailyRecords};for(let i=21;i<=27;i++)daily[`2026-09-${i}`]={date:`2026-09-${i}`,cells:{'7:0':String(i)}};
 r=await post(db,[action('UPDATE_BED',{patch:{dailyRecords:daily,dates:['2026-09-27','','','','',''],cells:{'0:7:0':'27'}}})]);assert.equal(r.status,200,JSON.stringify(await r.clone().json()));m=await loadPep(db);assert.equal(Object.keys(m.state.beds['01'].dailyRecords).length,8);assert.equal(m.state.beds['01'].evolutionDrafts['2026-09-20'],'RASCUNHO DOCUMENTADO');assert.equal(JSON.parse((await sql.prepare('SELECT data FROM daily_sheets').get()).data).dates.filter(Boolean).length,8);assert.equal((await sql.prepare('SELECT count(*) n FROM pep_revisions').get()).n,2);
});
test('alta preserva histórico e novo ocupante recebe ID novo; transferência preserva internação',async()=>{const{db,sql}=await database();assert.equal((await post(db,[action('SET_DATE',{day:0,value:'2026-09-20',cascade:false}),action('SET_CELL',{day:0,row:7,slot:0,value:'123'})])).status,200);assert.equal((await post(db,[action('DISCHARGE_BED')])).status,200);let m=await loadPep(db);assert.equal(m.state.archivedEpisodes.p1.cells['0:7:0'],'123');assert.equal((await sql.prepare('SELECT archived FROM patients WHERE id=?').get('p1')).archived,1);
 assert.equal((await post(db,[{type:'UPDATE_BED',bedId:'01',patch:{patientName:'OUTRO SINTÉTICO',age:'50'}}])).status,200);m=await loadPep(db);const b=m.state.beds['01'];assert.notEqual(b.patientId,'p1');assert.deepEqual(b.cells,{});
 assert.equal((await post(db,[{type:'MOVE_PATIENT',bedId:'01',toBedId:'02',patientId:b.patientId,episodeId:b.episodeId}])).status,200);m=await loadPep(db);assert.equal(m.state.beds['02'].patientId,b.patientId);assert.equal((await sql.prepare('SELECT bed FROM patients WHERE id=?').get(b.patientId)).bed,'02');assert.equal((await post(db,[action('SET_CELL',{day:0,row:7,slot:0,value:'ERRO'})])).status,400);
});
test('alteração em API legada é incorporada e invalida snapshot de geração',async()=>{const{db,sql}=await database();let r=await post(db,[action('SET_DATE',{day:0,value:'2026-09-20',cascade:false})]);assert.equal(r.status,200);const m=await loadPep(db);(await sql.prepare('UPDATE patients SET medical_history=?,updated_at=? WHERE id=?').run('ANTECEDENTE NOVO','2026-09-30T12:00:00Z','p1'));const next=await loadPep(db);assert.equal(next.state.beds['01'].handoff.antecedentes_historia[0],'ANTECEDENTE NOVO');assert.equal((await post(db,[action('SET_CELL',{day:0,row:7,slot:0,value:'456'})],m)).status,409);});
test('escritas rejeitam datas inválidas, IDs alterados e limpeza global; transação não aplica parcialmente',async()=>{const{db,sql}=await database();for(const a of [action('SET_DATE',{day:0,value:'2026-02-30'}),action('UPDATE_BED',{patch:{patientId:'fake'}}),{type:'RESET_ALL'}])assert.equal((await post(db,[action('SET_CELL',{day:0,row:7,slot:0,value:'111'}),a])).status,400);assert.equal((await sql.prepare('SELECT count(*) n FROM pep_revisions').get()).n,0);});
test('evolução antiga editada não substitui atual e prescrições mantêm parâmetros originais',async()=>{const{db}=await database();let r=await post(db,[action('UPDATE_BED',{patch:{evolutionDate:'2026-09-25'}}),action('SET_EVOLUCAO',{evolucao:{texto:'# HMA\nATUAL',payload:{resumo_internacao:'ATUAL'}}}),action('UPDATE_BED',{patch:{evolutionDate:'2026-09-20'}}),action('SET_EVOLUCAO',{evolucao:{texto:'# HMA\nANTIGA',payload:{resumo_internacao:'ANTIGA'}}}),action('UPDATE_BED',{patch:{prescriptions:[{id:'saved',text:'ORIGINAL',weight:60,rate:10}]}})]);assert.equal(r.status,200,JSON.stringify(await r.clone().json()));r=await post(db,[action('UPDATE_BED',{patch:{weight:{value:'80'}}})]);assert.equal(r.status,200);const m=await loadPep(db);assert.equal(m.state.beds['01'].evolucao.texto,'# HMA\nATUAL');assert.equal(m.state.beds['01'].prescriptions[0].weight,60);});
test('backup inclui revisões, todas as tabelas e contagens verificáveis',async()=>{const{db}=await database();await post(db,[action('SET_DATE',{day:0,value:'2026-09-20',cascade:false})]);const r=await handlePepApi(new Request('https://test/api/pep?op=backup'),db);assert.equal(r.status,200);const b=await r.json();assert.equal(b.tables.pep_revisions.length,1);assert.equal(b.tables.patients.length,b.counts.patients);});
test('agente sem segredo falha fechado; chamada sintética conserva provedor/modelo e contrato',async()=>{const{db}=await database();await post(db,[action('SET_DATE',{day:0,value:'2026-09-20',cascade:false})]);const m=await loadPep(db);const body={operation:'handoff',patients:[{bedId:'01',patientId:'p1',episodeId:'p1'}],version:m.version,sourceToken:m.sourceToken};const req=()=>new Request('https://test/api/pep/ai',{method:'POST',body:JSON.stringify(body)});assert.equal((await handlePepAI(req(),db,{apiKey:''})).status,503);let sent;
 const mock=mockClaude(b=>{sent=b;return {text:JSON.stringify({pacientes:[{leito:'01',nome:'PACIENTE SINTÉTICO',data_ficha:'2026-09-20',patient_id:'p1',episode_id:'p1',diagnosticos:[],antecedentes_historia:['ANTECEDENTE EXPLÍCITO'],historia_atual:[],condutas:[],pendencias:[]}]})};});try{const r=await handlePepAI(req(),db,KEY);assert.equal(r.status,200,JSON.stringify(await r.clone().json()));assert.equal(sent.model,'claude-opus-5-5');assert.equal(sent.stream,true);assert.equal(sent.fallbacks,'default');assert.match(mock.calls[0].headers.get('anthropic-beta'),/server-side-fallback-2026-07-01/);assert.equal(sent.output_config.format.type,'json_schema');assert.equal(sent.output_config.format.schema.additionalProperties,false);assert.deepEqual((await r.json()).patients[0].antecedentes_historia,['ANTECEDENTE EXPLÍCITO']);}finally{mock.restore();}});
test('reabrir dia antigo em nova folha preserva células e passagens de outras datas',async()=>{const{db}=await database();let r=await post(db,[action('SET_DATE',{day:0,value:'2026-09-20',cascade:false}),action('SET_CELL',{day:0,row:7,slot:0,value:'123'}),action('UPDATE_HANDOFF',{patch:{condutas:['PLANO DIA 20']}})]);assert.equal(r.status,200);r=await post(db,[action('UPDATE_BED',{patch:{dates:Array(6).fill(''),cells:{}}}),action('SET_DATE',{day:0,value:'2026-09-21',cascade:false}),action('UPDATE_HANDOFF',{patch:{condutas:['PLANO DIA 21']}})]);assert.equal(r.status,200);r=await post(db,[action('UPDATE_BED',{patch:{dates:Array(6).fill(''),cells:{}}}),action('SET_DATE',{day:0,value:'2026-09-20',cascade:false})]);assert.equal(r.status,200);const m=await loadPep(db);assert.equal(m.state.beds['01'].cells['0:7:0'],'123');assert.deepEqual(m.state.beds['01'].handoff.condutas,['PLANO DIA 20']);assert.deepEqual(m.state.beds['01'].handoffByDate['2026-09-21'].condutas,['PLANO DIA 21']);});

test('extração envia imagem como conteúdo multimodal e rejeita geração com origem alterada',async()=>{const{db}=await database();const m=await loadPep(db);const body={operation:'extract',patients:[{bedId:'01',patientId:'p1',episodeId:'p1'}],version:m.version,sourceToken:m.sourceToken,text:'TEXTO SINTÉTICO',image:'data:image/png;base64,aGVsbG8='};const req=()=>new Request('https://test/api/pep/ai',{method:'POST',body:JSON.stringify(body)});let sent;let mutate=false;const mock=mockClaude(async b=>{sent=b;if(mutate)await db.prepare("UPDATE patients SET summary=? WHERE id=?").bind('ALTERAÇÃO SINTÉTICA','p1').run();return {text:JSON.stringify({patient:'PACIENTE SINTÉTICO',admission:'20/09/2026',bed:'01',days:[{date:'20/09/2026',cells:[{row:7,slot:0,value:'1000'}]}]})};});try{const r=await handlePepAI(req(),db,KEY);assert.equal(r.status,200,JSON.stringify(await r.clone().json()));assert.deepEqual(sent.messages[0].content,[{type:'image',source:{type:'base64',media_type:'image/png',data:'aGVsbG8='}},{type:'text',text:body.text}]);assert.equal(sent.output_config.effort,'medium');assert.equal((await r.json()).extraction.days[0].cells['7'][0],'1000');mutate=true;assert.equal((await handlePepAI(req(),db,KEY)).status,409);}finally{mock.restore();}});

test('evolução legada tem metadados estáveis entre leituras e não impede conferência anterior à IA',async()=>{const{db}=await database();await db.prepare('INSERT INTO evolutions(patient_id,evolution_date,text,created_at,updated_at)VALUES(?,?,?,?,?)').bind('p1','2026-09-20','# HMA:\nHISTÓRIA SINTÉTICA','2026-09-20T10:00:00Z','2026-09-20T11:00:00Z').run();const a=await loadPep(db),b=await loadPep(db);assert.deepEqual(a.state.beds['01'],b.state.beds['01']);assert.equal(a.state.beds['01'].evolucao.editadoEm,'2026-09-20T11:00:00Z');});
test('passagem externa rejeita seleção incompleta e data ausente sem construir revisão parcial',async()=>{const{validateHandoffResponse}=await import('../app/pep/core/handoffGeneration.js');const bed={bedId:'01',patientId:'a',episodeId:'a',patientName:'SINTÉTICO',dates:['2026-09-20','','','','',''],cells:{}};const patient={leito:'01',nome:'SINTÉTICO',patient_id:'a',episode_id:'a',data_ficha:'2026-09-20',diagnosticos:[],antecedentes_historia:[],historia_atual:[],condutas:[],pendencias:[]};assert.throws(()=>validateHandoffResponse(JSON.stringify({pacientes:[patient]}),[bed,{...bed,bedId:'02',patientId:'b',episodeId:'b'}]),/todos os pacientes/);assert.throws(()=>validateHandoffResponse(JSON.stringify({pacientes:[{...patient,data_ficha:''}]}),[bed]),/data válida/);});

async function chartDoc(b){const{identityOf,chartToken,SUMMARY_SECTIONS,DAY_SECTIONS,CHART_HANDOFF}=await import('../app/pep/core/chartOrganization.js');return {...identityOf(b,await chartToken(b)),resumo_internacao:{...Object.fromEntries(Object.keys(SUMMARY_SECTIONS).map(k=>[k,''])),curso_clinico:'20/09/2026: HISTÓRIA DOCUMENTADA'},dias:[{data:'2026-09-20',secoes:{...Object.fromEntries(Object.keys(DAY_SECTIONS).map(k=>[k,''])),historia_intercorrencias:'EVOLUÇÃO ORGANIZADA',condutas:'PLANO DOCUMENTADO'},ficha:[{row:7,slot:0,value:'1500'}],passagem:Object.fromEntries(CHART_HANDOFF.map(k=>[k,[]]))}]};}
test('organização central persiste resumo, evolução, ficha e passagem por data, com autoria e recarga',async()=>{const{db,sql}=await database();const m=await loadPep(db),b=JSON.parse(JSON.stringify(m.state.beds['01'])),document=await chartDoc(b);const r=await post(db,[action('IMPORT_CHART',{document,choices:{},reviewVersion:m.version,metadata:{source:'external',sourceText:'FONTE SINTÉTICA',author:'autor forjado'}})],m);assert.equal(r.status,200,JSON.stringify(await r.clone().json()));const next=await loadPep(db),saved=next.state.beds['01'];assert.match(saved.hospitalizationSummary.texto,/HISTÓRIA DOCUMENTADA/);assert.equal(saved.hospitalizationSummary.author,'Usuário autenticado');assert.match(saved.dailyRecords['2026-09-20'].evolution.texto,/EVOLUÇÃO ORGANIZADA/);assert.equal(saved.dailyRecords['2026-09-20'].cells['7:0'],'1500');assert.deepEqual(saved.handoffByDate['2026-09-20'].condutas,['PLANO DOCUMENTADO']);assert.equal(saved.chartImports[0].sourceText,'FONTE SINTÉTICA');assert.equal((await sql.prepare('SELECT text FROM evolutions WHERE patient_id=? AND evolution_date=?').get('p1','2026-09-20')).text,saved.dailyRecords['2026-09-20'].evolution.texto);assert.equal(JSON.parse((await sql.prepare('SELECT data FROM daily_sheets').get()).data).cells['0:7:0'],'1500');assert.equal((await sql.prepare('SELECT count(*) n FROM patients').get()).n,1);});
test('organização rejeita vínculo obsoleto, paciente incorreto e lote misto sem escrever parcialmente',async()=>{const{db,sql}=await database();const m=await loadPep(db),document=await chartDoc(m.state.beds['01']);const base=action('IMPORT_CHART',{document,choices:{},reviewVersion:m.version,metadata:{source:'external',sourceText:''}});assert.equal((await post(db,[{...base,document:{...document,review_token:'0'.repeat(64)}}],m)).status,409);assert.equal((await post(db,[{...base,document:{...document,nome:'OUTRO'}}],m)).status,400);assert.equal((await post(db,[base,action('SET_DATE',{day:0,value:'2026-09-20'})],m)).status,409);assert.equal((await sql.prepare('SELECT count(*) n FROM pep_revisions').get()).n,0);assert.equal((await sql.prepare('SELECT count(*) n FROM evolutions').get()).n,0);});
test('IA de organização usa provedor vigente, fontes da internação e contrato com identidade; valida retorno',async()=>{const{db}=await database();const m=await loadPep(db),document=await chartDoc(m.state.beds['01']);const body={operation:'organize_chart',patients:[{bedId:'01',patientId:'p1',episodeId:'p1'}],version:m.version,sourceToken:m.sourceToken,text:'20/09/2026: TEXTO ADICIONAL SINTÉTICO'};const req=()=>new Request('https://test/api/pep/ai',{method:'POST',body:JSON.stringify(body)});let sent;let wrong=false;const mock=mockClaude(b=>{sent=b;return {text:JSON.stringify({...document,...(wrong?{episode_id:'outro'}:{})})};});try{const r=await handlePepAI(req(),db,KEY);assert.equal(r.status,200,JSON.stringify(await r.clone().json()));assert.equal((await r.json()).chart.episode_id,'p1');assert.equal(sent.model,'claude-opus-5-5');assert.equal(sent.output_config.format.schema.additionalProperties,false);assert.match(sent.messages[0].content,/registros_por_data/);assert.match(sent.messages[0].content,/TEXTO ADICIONAL SINTÉTICO/);wrong=true;assert.equal((await handlePepAI(req(),db,KEY)).status,400);}finally{mock.restore();}});
