'use client';

import {Fragment,useCallback,useEffect,useRef,useState} from 'react';
import {latestDay,useICU,type Patient,type Sheet} from './ICUContext';
import {FICHA_GROUPS,FICHA_ROWS,cellKey,clearDay,copyPrevious,fromBr,mergeBackup,mergeExtracted,toBr,type Extracted} from './fichaModel';
import {buildExtractionPrompt} from './extractionPrompt';

const numeric=/^[-+]?\d+(?:[.,]\d+)?$/;
const volume=(value:string)=>numeric.test(value.trim())?Number(value.trim().replace(',','.')):null;
function balance(sheet:Sheet,day:number){const input=volume(sheet.cells[cellKey(day,3,0)]||'');const losses=[[7,0],[8,0],[9,0],[9,1],[10,0]].map(([r,s])=>volume(sheet.cells[cellKey(day,r,s)]||''));return input!==null&&losses.every(n=>n!==null)?input-(losses as number[]).reduce((a,b)=>a+b,0):null;}
const readImage=(file:File)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(Error('Falha ao ler a imagem.'));r.readAsDataURL(file)});

export function FichaPrint({patient,sheet,containerRef,windowStart=0}:{patient:Patient;sheet:Sheet;containerRef:React.RefObject<HTMLDivElement|null>;windowStart?:number}){
 return <div className="icu-print-source" ref={containerRef}><div className="icu-print-paper"><table className="icu-print-table" aria-label="Ficha de evolução diária de UTI — seis dias">
  <colgroup><col className="group-col"/><col className="label-col"/><col className="label-col"/>{Array.from({length:12},(_,i)=><col className={`day-col day-${Math.floor(i/2)}`} key={i}/>)}</colgroup>
  <thead><tr className="hospital-row"><th colSpan={8}>HOSPITAL REGIONAL DE IVAIPORÃ</th><th colSpan={4}>ADMISSÃO<br/><span data-print-cell className="icu-print-value">{sheet.admission}</span></th><th colSpan={3}>LEITO<br/><span data-print-cell className="icu-print-value">{patient.bed}</span></th></tr>
  <tr className="patient-row"><th colSpan={15}><span>Paciente: </span><span data-print-cell className="icu-print-value patient-name">{patient.name}</span></th></tr>
  <tr className="date-row"><th colSpan={3}>Data</th>{Array.from({length:6},(_,i)=><th className={`day-${i}`} colSpan={2} key={i}><span data-print-cell className="icu-print-value">{sheet.dates[windowStart+i]||''}</span></th>)}</tr></thead>
  <tbody>{FICHA_GROUPS.flatMap(group=>group.rows.map((row,index)=><tr key={row.id} data-row={row.id}>
   {index===0&&<th className="section" rowSpan={group.rows.length}>{group.name}</th>}
   {row.single?<th className="label" colSpan={2}>{row.labels[0]}</th>:<><th className="label">{row.labels[0]}</th><th className="label">{row.labels[1]}</th></>}
   {Array.from({length:6},(_,slot)=>{const day=windowStart+slot;return row.single?<td className={`day-${slot}`} colSpan={2} key={slot}>{row.editable&&<span data-print-cell className="icu-print-value">{sheet.cells[cellKey(day,row.id,0)]||''}</span>}</td>:<Fragment key={slot}><td className={`day-${slot}`}><span data-print-cell className="icu-print-value">{sheet.cells[cellKey(day,row.id,0)]||''}</span></td><td className={`day-${slot}`}><span data-print-cell className="icu-print-value">{sheet.cells[cellKey(day,row.id,1)]||''}</span></td></Fragment>})}
  </tr>))}</tbody>
 </table></div></div>;
}

export default function Ficha({patient}:{patient:Patient}){
 const {sheets,updateSheetEntry}=useICU();const initial=sheets[patient.id];
 const [sheet,setSheet]=useState<Sheet>(()=>({...initial.sheet,patient:patient.name,bed:patient.bed,admission:initial.sheet.admission||toBr((patient.icuAdmissionAt||patient.admissionAt||'').slice(0,10))}));
 const [day,setDay]=useState(()=>Math.max(0,latestDay(sheet)));
 const windowStart=Math.max(0,day-5);
 const [status,setStatus]=useState('Ficha carregada'),[blocked,setBlocked]=useState(false),[preview,setPreview]=useState(false),[text,setText]=useState(initial.sheet.sourceText||''),[proposal,setProposal]=useState(''),[proposalStart,setProposalStart]=useState(0),[processing,setProcessing]=useState(false);
 const current=useRef(sheet),version=useRef(initial.version),dirty=useRef(false),locked=useRef(false),pending=useRef(0),timer=useRef<ReturnType<typeof setTimeout>|null>(null),queue=useRef<Promise<void>>(Promise.resolve()),printRef=useRef<HTMLDivElement>(null),mounted=useRef(true);
 const report=(value:string)=>{if(mounted.current)setStatus(value)};
 const flush=useCallback(()=>{
  if(timer.current){clearTimeout(timer.current);timer.current=null;}
  if(locked.current||!dirty.current)return queue.current;
  const snapshot=structuredClone(current.current);dirty.current=false;pending.current++;
  queue.current=queue.current.then(async()=>{
   const response=await fetch(`/api/ficha?patientId=${encodeURIComponent(patient.id)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sheet:snapshot,version:version.current})});
   const result=await response.json() as {version?:number;error?:string};
   if(!response.ok||typeof result.version!=='number')throw Error(result.error||'Falha ao salvar a ficha.');
   version.current=result.version;updateSheetEntry(patient.id,{sheet:snapshot,version:result.version});
   if(!dirty.current)report('Salvo');
  }).catch(e=>{dirty.current=true;locked.current=true;if(mounted.current)setBlocked(true);report(`${e instanceof Error?e.message:'Não foi possível salvar.'} Exporte uma cópia antes de sair.`);}).finally(()=>{pending.current--;});
  return queue.current;
 },[patient.id,updateSheetEntry]);
 const change=(next:Sheet)=>{if(locked.current)return;current.current=next;setSheet(next);dirty.current=true;report('Salvando…');if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void flush(),450);};
 useEffect(()=>{mounted.current=true;const warn=(e:BeforeUnloadEvent)=>{if(dirty.current||pending.current>0){e.preventDefault();e.returnValue='';}};const after=()=>{delete document.body.dataset.icuPrint};window.addEventListener('beforeunload',warn);window.addEventListener('afterprint',after);return()=>{mounted.current=false;window.removeEventListener('beforeunload',warn);window.removeEventListener('afterprint',after);if(timer.current)void flush();delete document.body.dataset.icuPrint};},[flush]);
 const applyProposal=()=>{try{const parsed=JSON.parse(proposal.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'')) as Extracted;if(!Array.isArray(parsed.days))throw Error('JSON sem a lista de dias.');const target=parsed.days.length===1&&!parsed.days[0]?.date?day:proposalStart;const result=mergeExtracted(current.current,parsed,target);change(result.sheet);report(`${result.added} célula(s) incluída(s); ${result.conflicts} divergência(s) preservada(s). Revise os dias exibidos.`);}catch(e){report(e instanceof Error?e.message:'JSON inválido.')}};
 async function interpret(payload:{text?:string;image?:string;day:number}){setProcessing(true);const start=Math.max(0,payload.day-5);try{const response=await fetch('/api/ficha/interpret',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,day:payload.day-start})});const result=await response.json() as Extracted&{error?:string};if(!response.ok)throw Error(result.error||'Falha na interpretação.');setProposalStart(start);setProposal(JSON.stringify(result,null,2));report('Dados extraídos. Confira paciente, datas e células antes de aplicar.');}catch(e){report(e instanceof Error?e.message:'Falha na interpretação.')}finally{setProcessing(false);}}
 function addDay(){if(blocked||sheet.dates.length>=730)return report('Limite de dias da ficha atingido; exporte o histórico para arquivamento.');const previous=fromBr(sheet.dates.at(-1)||'');if(!previous)return report('Preencha a data do último dia antes de adicionar o próximo.');const next=new Date(`${previous}T12:00:00Z`);if(Number.isNaN(next.getTime())||next.toISOString().slice(0,10)!==previous)return report('Corrija a data do último dia antes de continuar.');next.setUTCDate(next.getUTCDate()+1);const value=toBr(next.toISOString().slice(0,10));change({...current.current,dates:[...current.current.dates,value]});setDay(sheet.dates.length);report(`Dia ${sheet.dates.length+1} criado. Confira a data e preencha os valores atuais.`);}
 async function print(){await flush();await queue.current;if(dirty.current||locked.current){report('Impressão suspensa: a ficha ainda não foi salva. Exporte uma cópia e resolva o conflito.');return;}const overflow=[...(printRef.current?.querySelectorAll<HTMLElement>('[data-print-cell]')||[])].filter(e=>e.scrollWidth>e.clientWidth+1);if(overflow.length){report(`${overflow.length} campo(s) excedem a largura da ficha A4. Abrevie os valores antes de imprimir para evitar corte.`);return;}document.body.dataset.icuPrint='true';await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));window.print();}
 function download(){const blob=new Blob([JSON.stringify(current.current,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`ficha-uti-${patient.bed}-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const dayCount=FICHA_ROWS.filter(r=>r.editable).reduce((n,r)=>n+[0,1].filter(s=>(!r.single||s===0)&&sheet.cells[cellKey(day,r.id,s)]?.trim()).length,0);
 return <section className="icu-ficha-native">
  <div className="icu-ficha-head"><div><strong>Ficha diária · Dia {day+1}</strong><small>{dayCount} campo(s) preenchido(s) · folha com seis dias consecutivos</small></div><button type="button" onClick={()=>void print()} disabled={blocked}>Imprimir A4</button></div>
  <div className="icu-day-navigation"><button type="button" disabled={windowStart===0} onClick={()=>setDay(Math.max(0,day-6))}>Dias anteriores</button><span>D{windowStart+1} a D{windowStart+6}</span><button type="button" disabled={day>=Math.max(0,latestDay(sheet))} onClick={()=>setDay(Math.max(0,latestDay(sheet)))}>Mais recente</button></div>
  <div className="icu-day-tabs" role="tablist" aria-label="Dia da ficha">{Array.from({length:6},(_,i)=>{const index=windowStart+i;return <button key={index} type="button" role="tab" aria-selected={day===index} className={day===index?'active':''} disabled={index>=sheet.dates.length} onClick={()=>setDay(index)}>D{index+1}<small>{sheet.dates[index]?.slice(0,5)||'—'}</small></button>})}</div>
  {day===sheet.dates.length-1&&sheet.dates.length>=6&&<button type="button" className="icu-add-day" disabled={blocked} onClick={addDay}>Adicionar próximo dia à sequência</button>}
  <label className="icu-day-date">Data do Dia {day+1}<input type="date" value={fromBr(sheet.dates[day]||'')} onChange={e=>change({...sheet,dates:sheet.dates.map((v,i)=>i===day?toBr(e.target.value):v)})}/></label>
  <div className="icu-day-actions"><button type="button" disabled={day===0||blocked} onClick={()=>{if(window.confirm('Copiar somente para campos vazios? Confirme a atualidade de todos os valores do dia anterior.'))change(copyPrevious(current.current,day));}}>Copiar dia anterior</button><button type="button" disabled={blocked} onClick={()=>{if(window.confirm('Limpar todos os campos e a data deste dia? A alteração será auditada.'))change(clearDay(current.current,day));}}>Limpar dia</button></div>
  {FICHA_GROUPS.map(group=><details className="icu-ficha-group" key={group.name}><summary>{group.name}<span>{group.rows.reduce((n,row)=>n+[0,1].filter(s=>(!row.single||s===0)&&sheet.cells[cellKey(day,row.id,s)]?.trim()).length,0)}/{group.rows.reduce((n,r)=>n+(r.editable?(r.single?1:2):0),0)}</span></summary><div>{group.rows.map(row=><div className="icu-ficha-line" key={row.id}><span className="icu-line-label">{row.labels.filter(Boolean).join(' / ')||`Linha livre ${row.id}`}</span>{row.editable?<div className={row.single?'icu-cell-pair single':'icu-cell-pair'}>{Array.from({length:row.single?1:2},(_,slot)=><label key={slot}><span>{row.single?'Valor':row.labels[slot]||`Campo ${slot+1}`}</span><input data-input-cell value={sheet.cells[cellKey(day,row.id,slot)]||''} onChange={e=>change({...current.current,cells:{...current.current.cells,[cellKey(day,row.id,slot)]:e.target.value}})} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();const inputs=Array.from(e.currentTarget.closest('.icu-ficha-native')?.querySelectorAll<HTMLInputElement>('[data-input-cell]')||[]);inputs[inputs.indexOf(e.currentTarget)+1]?.focus();}}} aria-label={`${group.name}, linha ${row.id}, ${row.labels[slot]||'valor'}, Dia ${day+1}`}/></label>)}</div>:<span className="icu-blank-line">Linha vazia do modelo</span>}</div>)}</div></details>)}
  <div className="icu-balance-action"><button onClick={()=>{const result=balance(current.current,day);if(result===null)return report('Preencha entradas, diurese, diálise, fezes, estase e drenos em mL; informe zero somente se confirmado.');change({...current.current,cells:{...current.current.cells,[cellKey(day,12,0)]:String(result)}});}}>Calcular balanço hídrico</button><span>Entradas − perdas documentadas</span></div>
  <details className="icu-ficha-import"><summary>Prompt para IA externa</summary><div><p>Copie o prompt, anexe a imagem da ficha ao serviço autorizado e cole o JSON recebido no campo único da seção seguinte. Confira a identidade, as datas e cada valor antes de aplicar.</p><label>Prompt de extração<textarea className="icu-extraction-prompt" readOnly rows={9} value={buildExtractionPrompt(sheet,windowStart)} onFocus={e=>e.currentTarget.select()}/></label><button type="button" onClick={()=>void navigator.clipboard.writeText(buildExtractionPrompt(sheet,windowStart)).then(()=>report('Prompt copiado.'),()=>report('Falha ao copiar; selecione o texto do prompt.'))}>Copiar prompt de extração</button></div></details>
  <details className="icu-ficha-import"><summary>Preenchimento por texto, imagem ou JSON</summary><div><label>Texto contínuo<textarea rows={7} maxLength={40000} value={text} onChange={e=>{setText(e.target.value);change({...current.current,sourceText:e.target.value});}} placeholder="Cole os dados clínicos. A interpretação não substitui revisão médica."/></label><button disabled={processing||!text.trim()} onClick={()=>void interpret({text,day})}>Interpretar texto com IA</button><label>Imagem da ficha (JPEG, PNG ou WebP; até 4,5 MB)<input type="file" accept="image/jpeg,image/png,image/webp" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>4500000)return report('Imagem acima de 4,5 MB.');try{await interpret({image:await readImage(f),day});}catch(err){report(String(err));}}}/></label><label>Resposta JSON para conferência · D{proposalStart+1} a D{proposalStart+6}<textarea rows={9} value={proposal} onChange={e=>{setProposal(e.target.value);setProposalStart(windowStart)}} placeholder='{"patient":"...","days":[...]}'/></label><button disabled={!proposal.trim()||blocked} onClick={applyProposal}>Preencher após conferência</button><button onClick={download}>Exportar ficha JSON</button><label>Importar backup JSON desta ficha<input type="file" accept=".json,application/json" disabled={blocked} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>2000000)return report('Arquivo acima de 2 MB.');try{const result=mergeBackup(current.current,JSON.parse(await f.text()));if(window.confirm(`Importar ${result.added} campo(s) vazio(s)? ${result.conflicts} divergência(s) existente(s) serão preservadas.`)){change(result.sheet);report(`Backup incorporado: ${result.added} campo(s), ${result.conflicts} divergência(s) preservada(s).`);}}catch(err){report(err instanceof Error?err.message:'Backup inválido.')}finally{e.target.value='';}}}/></label></div></details>
  <button className="icu-ficha-preview-toggle" onClick={()=>setPreview(v=>!v)}>{preview?'Ocultar prévia A4':'Prévia da folha A4'}</button><div className={preview?'icu-print-preview visible':'icu-print-preview'}><FichaPrint patient={patient} sheet={sheet} windowStart={windowStart} containerRef={printRef}/></div>
  <p className={blocked?'icu-warning':'icu-save-status'} role="status">{status}</p>
 </section>;
}
